export interface Challenge {
    id: string;
    type: 'VERSE' | 'TRUTH';
    question: string;
    options: string[];
    answer: string;
}

const challengesES: Challenge[] = [
    // --- VERSÍCULOS ---
    { id: 'v1', type: 'VERSE', question: 'Todo lo puedo en __ que me fortalece.', options: ['Jesús', 'Dios', 'Cristo', 'Espíritu'], answer: 'Cristo' },
    { id: 'v2', type: 'VERSE', question: 'El __ es mi pastor, nada me faltará.', options: ['Señor', 'Dios', 'Rey', 'Padre'], answer: 'Señor' },
    { id: 'v3', type: 'VERSE', question: 'Lámpara es a mis pies tu __.', options: ['voz', 'luz', 'palabra', 'verdad'], answer: 'palabra' },
    { id: 'v4', type: 'VERSE', question: 'Jehová es mi __ y mi salvación.', options: ['roca', 'fuerza', 'luz', 'amparo'], answer: 'luz' },
    { id: 'v5', type: 'VERSE', question: 'No temas, porque yo estoy __.', options: ['aquí', 'contigo', 'mirando', 'cerca'], answer: 'contigo' },
    { id: 'v6', type: 'VERSE', question: 'En el principio creó Dios los cielos y la __.', options: ['tierra', 'vida', 'luz', 'noche'], answer: 'tierra' },
    { id: 'v7', type: 'VERSE', question: 'Yo soy el camino, la verdad y la __.', options: ['vida', 'luz', 'paz', 'fe'], answer: 'vida' },
    { id: 'v8', type: 'VERSE', question: 'Porque de tal manera amó Dios al __.', options: ['mundo', 'pueblo', 'hombre', 'justo'], answer: 'mundo' },
    { id: 'v9', type: 'VERSE', question: 'Honra a tu padre y a tu __.', options: ['madre', 'hermano', 'prójimo', 'abuelo'], answer: 'madre' },
    { id: 'v10', type: 'VERSE', question: 'El amor es sufrido, es __.', options: ['benigno', 'bueno', 'fiel', 'santo'], answer: 'benigno' },
    { id: 'v11', type: 'VERSE', question: 'Más bien, buscad primeramente el __ de Dios.', options: ['amor', 'reino', 'perdón', 'rostro'], answer: 'reino' },
    { id: 'v12', type: 'VERSE', question: 'Mira que te mando que te esfuerces y seas __.', options: ['fuerte', 'valiente', 'santo', 'fiel'], answer: 'valiente' },
    { id: 'v13', type: 'VERSE', question: 'En paz me acostaré, y asimismo __.', options: ['soñaré', 'descansaré', 'dormiré', 'confiaré'], answer: 'dormiré' },
    { id: 'v14', type: 'VERSE', question: 'El Señor es mi fuerza y mi __.', options: ['escudo', 'espada', 'roca', 'canción'], answer: 'escudo' },
    { id: 'v15', type: 'VERSE', question: 'Echando toda vuestra __ sobre él.', options: ['culpa', 'ansiedad', 'carga', 'duda'], answer: 'ansiedad' },
    { id: 'v16', type: 'VERSE', question: 'Y la paz de Dios, que sobrepasa todo __.', options: ['amor', 'entendimiento', 'poder', 'saber'], answer: 'entendimiento' },
    { id: 'v17', type: 'VERSE', question: 'El gozo del Señor es mi __.', options: ['fuerza', 'paz', 'vida', 'luz'], answer: 'fuerza' },
    { id: 'v18', type: 'VERSE', question: 'Instruye al niño en su __.', options: ['camino', 'verdad', 'vida', 'fe'], answer: 'camino' },
    { id: 'v19', type: 'VERSE', question: 'Crea en mí, oh Dios, un __ limpio.', options: ['espíritu', 'alma', 'corazón', 'ser'], answer: 'corazón' },
    { id: 'v20', type: 'VERSE', question: 'Yo soy la vid, vosotros los __.', options: ['frutos', 'pámpanos', 'siervos', 'hijos'], answer: 'pámpanos' },
    { id: 'v21', type: 'VERSE', question: 'Porque la paga del pecado es __.', options: ['muerte', 'dolor', 'juicio', 'tristeza'], answer: 'muerte' },
    { id: 'v22', type: 'VERSE', question: 'Mas la dádiva de Dios es vida __.', options: ['eterna', 'plena', 'sana', 'santa'], answer: 'eterna' },
    { id: 'v23', type: 'VERSE', question: 'Si confesamos nuestros __, él es fiel y justo.', options: ['errores', 'pecados', 'temores', 'fallos'], answer: 'pecados' },
    { id: 'v24', type: 'VERSE', question: 'Hacedlo todo para la gloria de __.', options: ['Cristo', 'Dios', 'Jesús', 'Padre'], answer: 'Dios' },
    { id: 'v25', type: 'VERSE', question: 'No os conforméis a este __.', options: ['mundo', 'tiempo', 'siglo', 'lugar'], answer: 'siglo' },
    { id: 'v26', type: 'VERSE', question: 'La fe es la certeza de lo que se __.', options: ['ve', 'siente', 'espera', 'cree'], answer: 'espera' },
    { id: 'v27', type: 'VERSE', question: 'Bienaventurados los de limpio __.', options: ['corazón', 'pensamiento', 'espíritu', 'camino'], answer: 'corazón' },
    { id: 'v28', type: 'VERSE', question: 'Vosotros sois la __ del mundo.', options: ['sal', 'luz', 'esperanza', 'fuerza'], answer: 'luz' },
    { id: 'v29', type: 'VERSE', question: 'Pedid, y se os __.', options: ['dará', 'abrirá', 'hará', 'oyera'], answer: 'dará' },
    { id: 'v30', type: 'VERSE', question: 'Clama a mí, y yo te __.', options: ['oiré', 'responderé', 'ayudaré', 'salvaré'], answer: 'responderé' },
    { id: 'v31', type: 'VERSE', question: 'Torre fuerte es el nombre de __.', options: ['Jesús', 'Dios', 'Jehová', 'Cristo'], answer: 'Jehová' },
    { id: 'v32', type: 'VERSE', question: 'El que habita al abrigo del __.', options: ['Omnipotente', 'Altísimo', 'Señor', 'Rey'], answer: 'Altísimo' },
    { id: 'v33', type: 'VERSE', question: 'Mis ovejas oyen mi __.', options: ['voz', 'llamado', 'silbido', 'palabra'], answer: 'voz' },
    { id: 'v34', type: 'VERSE', question: 'Y conoceréis la verdad, y la verdad os hará __.', options: ['sanos', 'libres', 'sabios', 'fuertes'], answer: 'libres' },
    { id: 'v35', type: 'VERSE', question: 'Nadie tiene mayor __ que este.', options: ['poder', 'fe', 'amor', 'esperanza'], answer: 'amor' },
    { id: 'v36', type: 'VERSE', question: 'Alzad vuestros ojos y mirad los __.', options: ['cielos', 'montes', 'campos', 'reinos'], answer: 'campos' },
    { id: 'v37', type: 'VERSE', question: 'Cercano está Jehová a los quebrantados de __.', options: ['espíritu', 'corazón', 'alma', 'vida'], answer: 'corazón' },
    { id: 'v38', type: 'VERSE', question: 'No nos ha dado Dios espíritu de __.', options: ['temor', 'cobardía', 'duda', 'ira'], answer: 'cobardía' },
    { id: 'v39', type: 'VERSE', question: 'Sino de poder, de amor y de __.', options: ['paz', 'fe', 'gozo', 'dominio propio'], answer: 'dominio propio' },
    { id: 'v40', type: 'VERSE', question: 'Si Dios es por nosotros, ¿quién contra __?', options: ['ti', 'nosotros', 'el mundo', 'todos'], answer: 'nosotros' },
    { id: 'v41', type: 'VERSE', question: 'Por nada estéis __.', options: ['tristes', 'afanosos', 'preocupados', 'cansados'], answer: 'afanosos' },
    { id: 'v42', type: 'VERSE', question: 'He guardado la __.', options: ['palabra', 'fe', 'verdad', 'ley'], answer: 'fe' },
    { id: 'v43', type: 'VERSE', question: 'He peleado la buena __.', options: ['guerra', 'batalla', 'lucha', 'carrera'], answer: 'batalla' },
    { id: 'v44', type: 'VERSE', question: 'Porque para mí el vivir es __.', options: ['Dios', 'ganancia', 'Cristo', 'amor'], answer: 'Cristo' },
    { id: 'v45', type: 'VERSE', question: 'Y el morir es __.', options: ['descanso', 'ganancia', 'paz', 'victoria'], answer: 'ganancia' },
    { id: 'v46', type: 'VERSE', question: 'Hijo mío, dame tu __.', options: ['vida', 'mano', 'corazón', 'alma'], answer: 'corazón' },
    { id: 'v47', type: 'VERSE', question: 'El temor de Jehová es el principio de la __.', options: ['vida', 'sabiduría', 'inteligencia', 'fe'], answer: 'sabiduría' },
    { id: 'v48', type: 'VERSE', question: 'Venid a mí todos los estáis trabajados y __.', options: ['cargados', 'cansados', 'tristes', 'enfermos'], answer: 'cargados' },
    { id: 'v49', type: 'VERSE', question: 'Y yo os haré __.', options: ['felices', 'descansar', 'fuertes', 'libres'], answer: 'descansar' },
    { id: 'v50', type: 'VERSE', question: 'Jesús lloró. Dijeron entonces: Mirad cómo le __.', options: ['quería', 'amaba', 'conocía', 'seguía'], answer: 'amaba' },
    // --- VERDADES ---
    { id: 't1', type: 'TRUTH', question: '¿Qué dice Dios sobre tu pasado?', options: ['Me juzga', 'Me condena', 'Me perdonó', 'Me ignora'], answer: 'Me perdonó' },
    { id: 't2', type: 'TRUTH', question: '¿Cómo te ve Dios?', options: ['Como pecador', 'Como hijo', 'Como siervo', 'Como extraño'], answer: 'Como hijo' },
    { id: 't3', type: 'TRUTH', question: 'Dios siempre está contigo, incluso en el silencio.', options: ['Verdadero', 'Falso'], answer: 'Verdadero' },
    { id: 't4', type: 'TRUTH', question: 'Tu valor depende de cuántos likes recibes.', options: ['Verdadero', 'Falso'], answer: 'Falso' },
    { id: 't5', type: 'TRUTH', question: 'Dios te creó con un propósito específico.', options: ['Verdadero', 'Falso'], answer: 'Verdadero' },
    { id: 't6', type: 'TRUTH', question: 'Tus errores son más grandes que la gracia de Dios.', options: ['Verdadero', 'Falso'], answer: 'Falso' },
    { id: 't7', type: 'TRUTH', question: 'La oración es hablar con tu Padre que te ama.', options: ['Verdadero', 'Falso'], answer: 'Verdadero' },
    { id: 't8', type: 'TRUTH', question: 'Necesitas ser perfecto para acercarte a Dios.', options: ['Verdadero', 'Falso'], answer: 'Falso' },
    { id: 't9', type: 'TRUTH', question: 'El Espíritu Santo vive dentro de ti.', options: ['Verdadero', 'Falso'], answer: 'Verdadero' },
    { id: 't10', type: 'TRUTH', question: 'Dios puede transformar cualquier situación para bien.', options: ['Verdadero', 'Falso'], answer: 'Verdadero' },
    { id: 't11', type: 'TRUTH', question: 'Eres amado con amor eterno.', options: ['Verdadero', 'Falso'], answer: 'Verdadero' },
    { id: 't12', type: 'TRUTH', question: 'La Biblia es solo un libro antiguo.', options: ['Verdadero', 'Falso'], answer: 'Falso' },
];

const challengesEN: Challenge[] = [
    { id: 'v1', type: 'VERSE', question: 'I can do all things through __ who strengthens me.', options: ['Jesus', 'God', 'Christ', 'Spirit'], answer: 'Christ' },
    { id: 'v2', type: 'VERSE', question: 'The __ is my shepherd; I shall not want.', options: ['Lord', 'God', 'King', 'Father'], answer: 'Lord' },
    { id: 'v3', type: 'VERSE', question: 'Your __ is a lamp to my feet.', options: ['voice', 'light', 'word', 'truth'], answer: 'word' },
    { id: 'v4', type: 'VERSE', question: 'The Lord is my __ and my salvation.', options: ['rock', 'strength', 'light', 'shield'], answer: 'light' },
    { id: 'v5', type: 'VERSE', question: 'Fear not, for I am __.', options: ['here', 'with you', 'watching', 'near'], answer: 'with you' },
    { id: 'v6', type: 'VERSE', question: 'In the beginning God created the heavens and the __.', options: ['earth', 'life', 'light', 'night'], answer: 'earth' },
    { id: 'v7', type: 'VERSE', question: 'I am the way, the truth, and the __.', options: ['life', 'light', 'peace', 'faith'], answer: 'life' },
    { id: 'v8', type: 'VERSE', question: 'For God so loved the __.', options: ['world', 'people', 'man', 'just'], answer: 'world' },
    { id: 'v9', type: 'VERSE', question: 'Honor your father and your __.', options: ['mother', 'brother', 'neighbor', 'friend'], answer: 'mother' },
    { id: 'v10', type: 'VERSE', question: 'Love is patient, love is __.', options: ['kind', 'good', 'faithful', 'holy'], answer: 'kind' },
    { id: 'v11', type: 'VERSE', question: 'But seek first the __ of God.', options: ['kingdom', 'love', 'face', 'power'], answer: 'kingdom' },
    { id: 'v12', type: 'VERSE', question: 'Be strong and __.', options: ['courageous', 'bold', 'faithful', 'holy'], answer: 'courageous' },
    { id: 'v13', type: 'VERSE', question: 'I will lie down and __ in peace.', options: ['sleep', 'rest', 'dream', 'wait'], answer: 'sleep' },
    { id: 'v14', type: 'VERSE', question: 'The Lord is my strength and my __.', options: ['shield', 'sword', 'rock', 'song'], answer: 'shield' },
    { id: 'v15', type: 'VERSE', question: 'Casting all your __ upon Him.', options: ['anxiety', 'care', 'fear', 'sin'], answer: 'anxiety' },
    { id: 'v16', type: 'VERSE', question: 'And the peace of God, which surpasses all __.', options: ['understanding', 'knowledge', 'wisdom', 'power'], answer: 'understanding' },
    { id: 'v17', type: 'VERSE', question: 'The joy of the Lord is my __.', options: ['strength', 'peace', 'life', 'hope'], answer: 'strength' },
    { id: 'v18', type: 'VERSE', question: 'Train up a child in the __ he should go.', options: ['way', 'path', 'truth', 'light'], answer: 'way' },
    { id: 'v19', type: 'VERSE', question: 'Create in me a clean __, O God.', options: ['heart', 'spirit', 'mind', 'soul'], answer: 'heart' },
    { id: 'v20', type: 'VERSE', question: 'I am the vine, you are the __.', options: ['branches', 'fruit', 'roots', 'leaves'], answer: 'branches' },
    { id: 'v21', type: 'VERSE', question: 'For the wages of sin is __.', options: ['death', 'pain', 'sorrow', 'guilt'], answer: 'death' },
    { id: 'v22', type: 'VERSE', question: 'But the gift of God is eternal __.', options: ['life', 'joy', 'peace', 'love'], answer: 'life' },
    { id: 'v23', type: 'VERSE', question: 'If we confess our __, He is faithful and just.', options: ['sins', 'faults', 'errors', 'fears'], answer: 'sins' },
    { id: 'v24', type: 'VERSE', question: 'Do all for the glory of __.', options: ['God', 'Christ', 'Jesus', 'Man'], answer: 'God' },
    { id: 'v25', type: 'VERSE', question: 'Do not be conformed to this __.', options: ['world', 'age', 'time', 'life'], answer: 'world' },
    { id: 'v26', type: 'VERSE', question: 'Faith is the substance of things __ for.', options: ['hoped', 'seen', 'wished', 'asked'], answer: 'hoped' },
    { id: 'v27', type: 'VERSE', question: 'Blessed are the pure in __.', options: ['heart', 'spirit', 'mind', 'soul'], answer: 'heart' },
    { id: 'v28', type: 'VERSE', question: 'You are the __ of the world.', options: ['light', 'salt', 'hope', 'strength'], answer: 'light' },
    { id: 'v29', type: 'VERSE', question: 'Ask, and it will be __ to you.', options: ['given', 'opened', 'shown', 'done'], answer: 'given' },
    { id: 'v30', type: 'VERSE', question: 'Call to Me, and I will __ you.', options: ['answer', 'hear', 'save', 'help'], answer: 'answer' },
    { id: 'v31', type: 'VERSE', question: 'The name of the Lord is a strong __.', options: ['tower', 'fortress', 'rock', 'shield'], answer: 'tower' },
    { id: 'v32', type: 'VERSE', question: 'He who dwells in the secret place of the __.', options: ['Most High', 'Almighty', 'Lord', 'King'], answer: 'Most High' },
    { id: 'v33', type: 'VERSE', question: 'My sheep hear My __.', options: ['voice', 'call', 'word', 'sound'], answer: 'voice' },
    { id: 'v34', type: 'VERSE', question: 'And you shall know the truth, and the truth shall make you __.', options: ['free', 'wise', 'strong', 'holy'], answer: 'free' },
    { id: 'v35', type: 'VERSE', question: 'Greater __ has no one than this.', options: ['love', 'faith', 'hope', 'power'], answer: 'love' },
    { id: 'v36', type: 'VERSE', question: 'Lift up your eyes and look at the __.', options: ['fields', 'mountains', 'heavens', 'hills'], answer: 'fields' },
    { id: 'v37', type: 'VERSE', question: 'The Lord is near to those who have a broken __.', options: ['heart', 'spirit', 'soul', 'will'], answer: 'heart' },
    { id: 'v38', type: 'VERSE', question: 'For God has not given us a spirit of __.', options: ['fear', 'timidity', 'power', 'love'], answer: 'fear' },
    { id: 'v39', type: 'VERSE', question: 'But of power and of love and of a sound __.', options: ['mind', 'heart', 'spirit', 'body'], answer: 'mind' },
    { id: 'v40', type: 'VERSE', question: 'If God is for us, who can be __ us?', options: ['against', 'with', 'above', 'below'], answer: 'against' },
    { id: 'v41', type: 'VERSE', question: 'Be __ for nothing.', options: ['anxious', 'afraid', 'worried', 'sad'], answer: 'anxious' },
    { id: 'v42', type: 'VERSE', question: 'I have kept the __.', options: ['faith', 'word', 'law', 'truth'], answer: 'faith' },
    { id: 'v43', type: 'VERSE', question: 'I have fought the good __.', options: ['fight', 'battle', 'race', 'war'], answer: 'fight' },
    { id: 'v44', type: 'VERSE', question: 'For to me, to live is __.', options: ['Christ', 'gain', 'God', 'love'], answer: 'Christ' },
    { id: 'v45', type: 'VERSE', question: 'And to die is __.', options: ['gain', 'loss', 'peace', 'rest'], answer: 'gain' },
    { id: 'v46', type: 'VERSE', question: 'My son, give me your __.', options: ['heart', 'hand', 'life', 'soul'], answer: 'heart' },
    { id: 'v47', type: 'VERSE', question: 'The fear of the Lord is the beginning of __.', options: ['wisdom', 'knowledge', 'understanding', 'life'], answer: 'wisdom' },
    { id: 'v48', type: 'VERSE', question: 'Come to Me, all you who labor and are heavy __.', options: ['laden', 'burdened', 'tired', 'weary'], answer: 'laden' },
    { id: 'v49', type: 'VERSE', question: 'And I will give you __.', options: ['rest', 'peace', 'strength', 'joy'], answer: 'rest' },
    { id: 'v50', type: 'VERSE', question: 'Jesus wept. Then the Jews said, "See how He __ him!"', options: ['loved', 'knew', 'liked', 'missed'], answer: 'loved' },
    // --- TRUTHS ---
    { id: 't1', type: 'TRUTH', question: 'What does God say about your past?', options: ['Condemns me', 'Forgave me', 'Judges me', 'Ignores me'], answer: 'Forgave me' },
    { id: 't2', type: 'TRUTH', question: 'How does God see you?', options: ['As a child', 'As a sinner', 'As a servant', 'As a stranger'], answer: 'As a child' },
    { id: 't3', type: 'TRUTH', question: 'God is always with you, even in silence.', options: ['True', 'False'], answer: 'True' },
    { id: 't4', type: 'TRUTH', question: 'Your worth depends on likes.', options: ['True', 'False'], answer: 'False' },
    { id: 't5', type: 'TRUTH', question: 'God created you with a specific purpose.', options: ['True', 'False'], answer: 'True' },
    { id: 't6', type: 'TRUTH', question: 'Your mistakes are greater than God\'s grace.', options: ['True', 'False'], answer: 'False' },
    { id: 't7', type: 'TRUTH', question: 'Prayer is talking to your Father who loves you.', options: ['True', 'False'], answer: 'True' },
    { id: 't8', type: 'TRUTH', question: 'You need to be perfect to approach God.', options: ['True', 'False'], answer: 'False' },
    { id: 't9', type: 'TRUTH', question: 'The Holy Spirit lives inside you.', options: ['True', 'False'], answer: 'True' },
    { id: 't10', type: 'TRUTH', question: 'God can transform any situation for good.', options: ['True', 'False'], answer: 'True' },
    { id: 't11', type: 'TRUTH', question: 'You are loved with an everlasting love.', options: ['True', 'False'], answer: 'True' },
    { id: 't12', type: 'TRUTH', question: 'The Bible is just an old book.', options: ['True', 'False'], answer: 'False' },
];

const challengesPT: Challenge[] = [
    { id: 'v1', type: 'VERSE', question: 'Posso todas as coisas em __ que me fortalece.', options: ['Cristo', 'Deus', 'Jesus', 'Espírito'], answer: 'Cristo' },
    { id: 'v2', type: 'VERSE', question: 'O __ é o meu pastor, nada me faltará.', options: ['Senhor', 'Deus', 'Rei', 'Pai'], answer: 'Senhor' },
    { id: 'v3', type: 'VERSE', question: 'Lâmpada para os meus pés é tua __.', options: ['palavra', 'luz', 'voz', 'verdade'], answer: 'palavra' },
    { id: 'v4', type: 'VERSE', question: 'O Senhor é a minha __ e a minha salvação.', options: ['luz', 'rocha', 'força', 'espada'], answer: 'luz' },
    { id: 'v5', type: 'VERSE', question: 'Não temas, porque eu sou __.', options: ['contigo', 'aqui', 'tua luz', 'teu Deus'], answer: 'contigo' },
    { id: 'v6', type: 'VERSE', question: 'No princípio criou Deus os céus e a __.', options: ['terra', 'vida', 'luz', 'noite'], answer: 'terra' },
    { id: 'v7', type: 'VERSE', question: 'Eu sou o caminho, a verdade e a __.', options: ['vida', 'luz', 'paz', 'fé'], answer: 'vida' },
    { id: 'v8', type: 'VERSE', question: 'Porque Deus amou o __ de tal maneira.', options: ['mundo', 'povo', 'homem', 'justo'], answer: 'mundo' },
    { id: 'v9', type: 'VERSE', question: 'Honra a teu pai e a tua __.', options: ['mãe', 'irmã', 'família', 'avó'], answer: 'mãe' },
    { id: 'v10', type: 'VERSE', question: 'O amor é sofredor, é __.', options: ['benigno', 'bom', 'fiel', 'santo'], answer: 'benigno' },
    { id: 'v11', type: 'VERSE', question: 'Mas buscai primeiro o __ de Deus.', options: ['reino', 'amor', 'perdão', 'rosto'], answer: 'reino' },
    { id: 'v12', type: 'VERSE', question: 'Esforça-te, e tem bom __.', options: ['ânimo', 'coração', 'espíritu', 'pensamento'], answer: 'ânimo' },
    { id: 'v13', type: 'VERSE', question: 'Em paz também me deitarei e __.', options: ['dormirei', 'descansarei', 'sonharei', 'esperarei'], answer: 'dormirei' },
    { id: 'v14', type: 'VERSE', question: 'O Senhor é a minha força e o meu __.', options: ['escudo', 'cântico', 'rocha', 'amparo'], answer: 'escudo' },
    { id: 'v15', type: 'VERSE', question: 'Lançando sobre ele toda a vossa __.', options: ['ansiedade', 'culpa', 'carga', 'dúvida'], answer: 'ansiedade' },
    { id: 'v16', type: 'VERSE', question: 'E a paz de Deus, que excede todo o __.', options: ['entendimento', 'saber', 'poder', 'amor'], answer: 'entendimento' },
    { id: 'v17', type: 'VERSE', question: 'A alegria do Senhor é a vossa __.', options: ['força', 'paz', 'vida', 'luz'], answer: 'força' },
    { id: 'v18', type: 'VERSE', question: 'Instrui o menino no __ em que deve andar.', options: ['caminho', 'verdade', 'luz', 'passo'], answer: 'caminho' },
    { id: 'v19', type: 'VERSE', question: 'Cria em mim, ó Deus, um __ puro.', options: ['coração', 'espíritu', 'alma', 'ser'], answer: 'coração' },
    { id: 'v20', type: 'VERSE', question: 'Eu sou a videira, vós as __.', options: ['varas', 'frutos', 'raízes', 'folhas'], answer: 'varas' },
    { id: 'v21', type: 'VERSE', question: 'Porque o salário do pecado é a __.', options: ['morte', 'dor', 'tristeza', 'culpa'], answer: 'morte' },
    { id: 'v22', type: 'VERSE', question: 'Mas o dom gratuito de Deus é a vida __.', options: ['eterna', 'plena', 'santa', 'nova'], answer: 'eterna' },
    { id: 'v23', type: 'VERSE', question: 'Se confessarmos os nossos __, ele é fiel e justo.', options: ['pecados', 'erros', 'falhas', 'medos'], answer: 'pecados' },
    { id: 'v24', type: 'VERSE', question: 'Fazei tudo para a glória de __.', options: ['Deus', 'Cristo', 'Jesus', 'Pai'], answer: 'Deus' },
    { id: 'v25', type: 'VERSE', question: 'E não sede conformados com este __.', options: ['mundo', 'século', 'tempo', 'lugar'], answer: 'mundo' },
    { id: 'v26', type: 'VERSE', question: 'Ora, a fé é o firme fundamento das coisas que se __.', options: ['esperam', 'veem', 'creem', 'pedem'], answer: 'esperam' },
    { id: 'v27', type: 'VERSE', question: 'Bem-aventurados os limpos de __.', options: ['coração', 'mãos', 'alma', 'mente'], answer: 'coração' },
    { id: 'v28', type: 'VERSE', question: 'Vós sois a __ do mundo.', options: ['luz', 'sal', 'esperança', 'força'], answer: 'luz' },
    { id: 'v29', type: 'VERSE', question: 'Pedi, e dar-se-vos-__.', options: ['á', 'ia', 'ei', 'rá'], answer: 'á' },
    { id: 'v30', type: 'VERSE', question: 'Clama a mim, e responder-te-__.', options: ['ei', 'ia', 'á', 'ai'], answer: 'ei' },
    { id: 'v31', type: 'VERSE', question: 'Torre forte é o nome do __.', options: ['Senhor', 'Deus', 'Rei', 'Pai'], answer: 'Senhor' },
    { id: 'v32', type: 'VERSE', question: 'Aquele que habita no esconderijo do __.', options: ['Altíssimo', 'Onipotente', 'Senhor', 'Rei'], answer: 'Altíssimo' },
    { id: 'v33', type: 'VERSE', question: 'As minhas ovelhas ouvem a minha __.', options: ['voz', 'palavra', 'chamado', 'assobio'], answer: 'voz' },
    { id: 'v34', type: 'VERSE', question: 'E conhecereis a verdade, e a verdade vos __.', options: ['libertará', 'salvará', 'curará', 'guiará'], answer: 'libertará' },
    { id: 'v35', type: 'VERSE', question: 'Ninguém tem maior __ do que este.', options: ['amor', 'fé', 'poder', 'esperança'], answer: 'amor' },
    { id: 'v36', type: 'VERSE', question: 'Levantai os vossos olhos, e vede as __.', options: ['terras', 'montanhas', 'nuvens', 'estrelas'], answer: 'terras' },
    { id: 'v37', type: 'VERSE', question: 'Perto está o Senhor dos que têm o __ quebrantado.', options: ['coração', 'espíritu', 'alma', 'ser'], answer: 'coração' },
    { id: 'v38', type: 'VERSE', question: 'Porque Deus não nos deu o espírito de __.', options: ['temor', 'medo', 'dúvida', 'covardia'], answer: 'temor' },
    { id: 'v39', type: 'VERSE', question: 'Mas de fortaleza, e de amor, e de __.', options: ['moderação', 'paz', 'alegria', 'fé'], answer: 'moderação' },
    { id: 'v40', type: 'VERSE', question: 'Se Deus é por nós, quem será contra __?', options: ['nós', 'ti', 'o mundo', 'todos'], answer: 'nós' },
    { id: 'v41', type: 'VERSE', question: 'Não estejais inquietos por __.', options: ['coisa alguma', 'nada', 'ninguém', 'o amanhã'], answer: 'coisa alguma' },
    { id: 'v42', type: 'VERSE', question: 'Guardei a __.', options: ['fé', 'palavra', 'lei', 'verdade'], answer: 'fé' },
    { id: 'v43', type: 'VERSE', question: 'Combati o bom __.', options: ['combate', 'jogo', 'caminho', 'teste'], answer: 'combate' },
    { id: 'v44', type: 'VERSE', question: 'Porque para mim o viver é __.', options: ['Cristo', 'Deus', 'lucro', 'amor'], answer: 'Cristo' },
    { id: 'v45', type: 'VERSE', question: 'E o morrer é __.', options: ['ganho', 'perda', 'paz', 'descanso'], answer: 'ganho' },
    { id: 'v46', type: 'VERSE', question: 'Dá-me, filho meu, o teu __.', options: ['coração', 'tempo', 'amor', 'pensamento'], answer: 'coração' },
    { id: 'v47', type: 'VERSE', question: 'O temor do Senhor é o princípio da __.', options: ['sabedoria', 'ciência', 'vida', 'fé'], answer: 'sabedoria' },
    { id: 'v48', type: 'VERSE', question: 'Vinde a mim, todos os que estais cansados e __.', options: ['oprimidos', 'carregados', 'tristes', 'doentes'], answer: 'oprimidos' },
    { id: 'v49', type: 'VERSE', question: 'E eu vos __.', options: ['aliviarei', 'curarei', 'salvarei', 'amarei'], answer: 'aliviarei' },
    { id: 'v50', type: 'VERSE', question: 'Jesus chorou. Disseram, pois, os judeus: Vede como o __.', options: ['amava', 'queria', 'conhecia', 'seguia'], answer: 'amava' },
    // --- VERDADES ---
    { id: 't1', type: 'TRUTH', question: 'O que Deus diz sobre o seu passado?', options: ['Perdoou-me', 'Condena-me', 'Julga-me', 'Ignora-me'], answer: 'Perdoou-me' },
    { id: 't2', type: 'TRUTH', question: 'Como Deus te vê?', options: ['Como filho', 'Como pecador', 'Como servo', 'Como estranho'], answer: 'Como filho' },
    { id: 't3', type: 'TRUTH', question: 'Deus está sempre com você, mesmo no silêncio.', options: ['Verdadeiro', 'Falso'], answer: 'Verdadeiro' },
    { id: 't4', type: 'TRUTH', question: 'Seu valor depende de quantos likes você recebe.', options: ['Verdadeiro', 'Falso'], answer: 'Falso' },
    { id: 't5', type: 'TRUTH', question: 'Deus te criou com um propósito específico.', options: ['Verdadeiro', 'Falso'], answer: 'Verdadeiro' },
    { id: 't6', type: 'TRUTH', question: 'Seus erros são maiores que a graça de Deus.', options: ['Verdadeiro', 'Falso'], answer: 'Falso' },
    { id: 't7', type: 'TRUTH', question: 'A oração é falar com seu Pai que te ama.', options: ['Verdadeiro', 'Falso'], answer: 'Verdadeiro' },
    { id: 't8', type: 'TRUTH', question: 'Você precisa ser perfeito para se aproximar de Deus.', options: ['Verdadeiro', 'Falso'], answer: 'Falso' },
    { id: 't9', type: 'TRUTH', question: 'O Espírito Santo vive dentro de você.', options: ['Verdadeiro', 'Falso'], answer: 'Verdadeiro' },
    { id: 't10', type: 'TRUTH', question: 'Deus pode transformar qualquer situação para o bem.', options: ['Verdadeiro', 'Falso'], answer: 'Verdadeiro' },
    { id: 't11', type: 'TRUTH', question: 'Você é amado com amor eterno.', options: ['Verdadeiro', 'Falso'], answer: 'Verdadeiro' },
    { id: 't12', type: 'TRUTH', question: 'A Bíblia é apenas um livro antigo.', options: ['Verdadeiro', 'Falso'], answer: 'Falso' },
];

export const getChallenges = (lang: 'es' | 'en' | 'pt'): Challenge[] => {
    switch (lang) {
        case 'en': return challengesEN;
        case 'pt': return challengesPT;
        default: return challengesES;
    }
};

// Kept for backward compatibility
export const challengeData = challengesES;
