export interface Verse {
    text: string;
    reference: string;
    text_en?: string;
    text_pt?: string;
    reference_en?: string;
    reference_pt?: string;
}

export const verses: Verse[] = [
    {
        text: "Aunque ande en valle de sombra de muerte, no temeré mal alguno, porque tú estarás conmigo.",
        reference: "Salmos 23:4",
        text_en: "Even though I walk through the darkest valley, I will fear no evil, for you are with me.",
        reference_en: "Psalm 23:4",
        text_pt: "Ainda que eu ande pelo vale da sombra da morte, não temerei mal algum, porque tu estás comigo.",
        reference_pt: "Salmos 23:4"
    },
    {
        text: "Entonces no sería yo avergonzado.",
        reference: "Salmos 119:6",
        text_en: "Then I would not be put to shame.",
        reference_en: "Psalm 119:6",
        text_pt: "Então não seria eu envergonhado.",
        reference_pt: "Salmos 119:6"
    },
    { text: "Mi alto refugio.", reference: "Salmos 18:2" },
    { text: "Porque para mí el vivir es Cristo, y el morir es ganancia.", reference: "Filipenses 1:21" },
    { text: "La blanda respuesta quita la ira.", reference: "Proverbios 15:1" },
    { text: "Al atender a todos tus mandamientos.", reference: "Salmos 119:6" },
    { text: "Todo tiene su tiempo.", reference: "Eclesiastés 3:1" },
    { text: "Estando afligido en gran manera.", reference: "Salmos 116:10" },
    { text: "Sobre los cielos su gloria.", reference: "Salmos 113:4" },
    { text: "Yo soy la luz del mundo; el que me sigue, no andará en tinieblas, sino que tendrá la luz de la vida.", reference: "Juan 8:12" },
    { text: "En mi angustia invoqué a Jehová, y clamé a mi Dios.", reference: "Salmos 18:6" },
    { text: "Él es el que nos hizo, y no nosotros a nosotros mismos.", reference: "Salmos 100:3" },
    { text: "Alabad a Jehová, porque él es bueno.", reference: "Salmos 118:1" },
    { text: "En él confiaré; mi escudo, y la fuerza de mi salvación.", reference: "Salmos 18:2" },
    { text: "La bondad y la misericordia me seguirán todos los días de mi vida.", reference: "Salmos 23:6" },
    { text: "Adoren al Señor con regocijo.", reference: "Salmos 100:2" },
    { text: "Mi socorro viene de Jehová, que hizo los cielos y la tierra.", reference: "Salmos 121:2" },
    { text: "Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.", reference: "Juan 14:6" },
    { text: "Y todo lo que hagan, de palabra o de obra, háganlo todo en el nombre del Señor Jesús, dando gracias a Dios el Padre por medio de él.", reference: "Colosenses 3:17" },
    { text: "Gloriaos en su santo nombre.", reference: "Salmos 105:3" },
    { text: "El que persevera hasta el fin, este será salvo.", reference: "Mateo 24:13" },
    { text: "Te alabaré con rectitud de corazón.", reference: "Salmos 119:7" },
    { text: "Mi libertador, Dios mío, fortaleza mía.", reference: "Salmos 18:2" },
    { text: "Mira mi aflicción, y líbrame.", reference: "Salmos 119:153" },
    { text: "El que tenga sed, venga.", reference: "Apocalipsis 22:17" },
    { text: "Este es el día que hizo Jehová; nos gozaremos y alegraremos en él.", reference: "Salmos 118:24" },
    { text: "El Señor es mi roca.", reference: "Salmos 18:2" },
    { text: "Desde la casa de Jehová os bendecimos.", reference: "Salmos 118:26" },
    { text: "Nadie te menosprecie por ser joven. Al contrario, que los creyentes vean en ti un ejemplo a seguir en la manera de hablar, en la conducta, y en amor, fe y pureza.", reference: "1 Timoteo 4:12" },
    { text: "Mi Dios eres tú, y te alabaré.", reference: "Salmos 118:28" },
    { text: "No se inquieten por nada; más bien, en toda ocasión, con oración y ruego, presenten sus peticiones a Dios y denle gracias.", reference: "Filipenses 4:6" },
    { text: "Alegraos siempre en el Señor. Otra vez digo: ¡Alegraos!", reference: "Filipenses 4:4" },
    { text: "Porque tanto amó Dios al mundo que dio a su Hijo unigénito, para que todo el que cree en él no se pierda, sino que tenga vida eterna.", reference: "Juan 3:16" },
    { text: "En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.", reference: "Juan 16:33" },
    { text: "Sea alabado el nombre de Jehová.", reference: "Salmos 113:3" },
    { text: "Por ella entrarán los justos.", reference: "Salmos 118:20" },
    { text: "Sin fe es imposible agradar a Dios.", reference: "Hebreos 11:6" },
    { text: "Llevad mi yugo sobre vosotros.", reference: "Mateo 11:29" },
    { text: "Siete veces cae el justo, y vuelve a levantarse.", reference: "Proverbios 24:16" },
    { text: "Tú has roto mis prisiones.", reference: "Salmos 116:16" },
    { text: "Jehová mi Dios alumbrará mis tinieblas.", reference: "Salmos 18:28" },
    { text: "Escudo es a todos los que en él esperan.", reference: "Salmos 18:30" },
    { text: "Delante de todo su pueblo.", reference: "Salmos 116:14" },
    { text: "Dejad a los niños venir a mí, y no se lo impidáis; porque de los tales es el reino de Dios.", reference: "Marcos 10:14" },
    { text: "Por tanto, id, y haced discípulos a todas las naciones.", reference: "Mateo 28:19" },
    { text: "Como aguas frías al alma sedienta, así son las buenas nuevas.", reference: "Proverbios 25:25" },
    { text: "Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.", reference: "Filipenses 4:7" },
    { text: "Porque el Espíritu que Dios nos ha dado no nos hace cobardes, sino que nos da poder, amor y dominio propio.", reference: "2 Timoteo 1:7" },
    { text: "En cuanto a Dios, perfecto es su camino.", reference: "Salmos 18:30" },
    { text: "La exposición de tus palabras alumbra.", reference: "Salmos 119:130" },
    { text: "Cantadle, cantadle salmos.", reference: "Salmos 105:2" },
    { text: "Clemente es Jehová, y justo.", reference: "Salmos 116:5" },
    { text: "Amén, Aleluya.", reference: "Apocalipsis 19:4" },
    { text: "Bienaventurados los que guardan sus testimonios.", reference: "Salmos 119:2" },
    { text: "Alabadle, bendecid su nombre.", reference: "Salmos 100:4" },
    { text: "Oh Jehová, sálvanos ahora, te ruego.", reference: "Salmos 118:25" },
    { text: "El corazón alegre hermosea el rostro.", reference: "Proverbios 15:13" },
    { text: "Jehová está conmigo; no temeré lo que me pueda hacer el hombre.", reference: "Salmos 118:6" },
    { text: "Toda la Escritura es inspirada por Dios.", reference: "2 Timoteo 3:16" },
    { text: "Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo en dondequiera que vayas.", reference: "Josué 1:9" },
    { text: "Tú encargaste que sean muy guardados tus mandamientos.", reference: "Salmos 119:4" },
    { text: "Repartió, dio a los pobres.", reference: "Salmos 112:9" },
    { text: "Con mis labios he contado todos los juicios de tu boca.", reference: "Salmos 119:13" },
    { text: "Estad quietos, y conoced que yo soy Dios.", reference: "Salmos 46:10" },
    { text: "Aleluya, Bienaventurados los perfectos de camino.", reference: "Salmos 119:1" },
    { text: "Los que andan en la ley de Jehová.", reference: "Salmos 119:1" },
    { text: "En los mandamientos de Dios se deleita en gran manera.", reference: "Salmos 112:1" },
    { text: "Pues tú has librado mi alma de la muerte.", reference: "Salmos 116:8" },
    { text: "No me olvidaré de tus palabras.", reference: "Salmos 119:16" },
    { text: "Jehová es mi fortaleza y mi escudo.", reference: "Salmos 28:7" },
    { text: "Clama a mí, y yo te responderé, y te enseñaré cosas grandes y ocultas que tú no conoces.", reference: "Jeremías 33:3" },
    { text: "Alabad, siervos de Jehová.", reference: "Salmos 113:1" },
    { text: "Hijo mío, dame tu corazón.", reference: "Proverbios 23:26" },
    { text: "Hace entender a los simples.", reference: "Salmos 119:130" },
    { text: "En mi corazón he guardado tus dichos.", reference: "Salmos 119:11" },
    { text: "Lámpara es a mis pies tu palabra, y lumbrera a mi camino.", reference: "Salmos 119:105" },
    { text: "El mismo Dios de paz os santifique.", reference: "1 Tesalonicenses 5:23" },
    { text: "El amor nunca deja de ser.", reference: "1 Corintios 13:8" },
    { text: "No tendrá temor de malas noticias.", reference: "Salmos 112:7" },
    { text: "Porque yo sé muy bien los planes que tengo para ustedes —afirma el Señor—, planes de bienestar y no de calamidad, a fin de darles un futuro y una esperanza.", reference: "Jeremías 29:11" },
    { text: "Maranatha.", reference: "1 Corintios 16:22" },
    { text: "Diga ahora Israel.", reference: "Salmos 118:2" },
    { text: "Humillaos, pues, bajo la poderosa mano de Dios, para que él os exalte cuando fuere tiempo.", reference: "1 Pedro 5:6" },
    { text: "Y guarde tu palabra.", reference: "Salmos 119:17" },
    { text: "Y mis pies no han resbalado.", reference: "Salmos 18:36" },
    { text: "Fíate de Jehová de todo tu corazón.", reference: "Proverbios 3:5" },
    { text: "Bienes y riquezas hay en su casa.", reference: "Salmos 112:3" },
    { text: "El Señor de paz os dé siempre paz en toda manera.", reference: "2 Tesalonicenses 3:16" },
    { text: "Porque el Hijo del Hombre vino a buscar y a salvar lo que se había perdido.", reference: "Lucas 19:10" },
    { text: "Todo lo puedo en Cristo que me fortalece.", reference: "Filipenses 4:13" },
    { text: "Y mis pies de resbalar.", reference: "Salmos 116:8" },
    { text: "Cantad salmos a su nombre.", reference: "Salmos 68:4" },
    { text: "Jehová dio, y Jehová quitó.", reference: "Job 1:21" },
    { text: "Jehová guarda a los sencillos.", reference: "Salmos 116:6" },
    { text: "Saludad a todos los hermanos con ósculo santo.", reference: "1 Tesalonicenses 5:26" },
    { text: "No temas, gusanito de Jacob.", reference: "Isaías 41:14" },
    { text: "Venid, benditos de mi Padre.", reference: "Mateo 25:34" },
    { text: "El ángel de Jehová acampa alrededor de los que le temen.", reference: "Salmos 34:7" },
    { text: "¡Viva Jehová, y bendita sea mi roca!", reference: "Salmos 18:46" },
    { text: "Me regocijaré en tus estatutos.", reference: "Salmos 119:16" },
    { text: "Cristo nos hizo libres.", reference: "Gálatas 5:1" },
    { text: "Y él ha sido mi salvación.", reference: "Salmos 118:14" },
    { text: "Con todo mi corazón te he buscado.", reference: "Salmos 119:10" },
    { text: "Su verdad por todas las generaciones.", reference: "Salmos 100:5" },
    { text: "Gracia y paz a vosotros, de Dios nuestro Padre y del Señor Jesucristo.", reference: "1 Corintios 1:3" },
    { text: "Gracia a vosotros y paz.", reference: "Romanos 1:7" },
    { text: "Pedid por la paz de Jerusalén.", reference: "Salmos 122:6" },
    { text: "Me libró, porque se agradó de mí.", reference: "Salmos 18:19" },
    { text: "Por sus llagas fuimos nosotros curados.", reference: "Isaías 53:5" },
    { text: "Enséñame tus estatutos.", reference: "Salmos 119:12" },
    { text: "Andan en sus caminos.", reference: "Salmos 119:3" },
    { text: "La fe es la certeza de lo que se espera.", reference: "Hebreos 11:1" },
    { text: "Gozaos con los que se gozan; llorad con los que lloran.", reference: "Romanos 12:15" },
    { text: "Él levanta del polvo al pobre.", reference: "Salmos 113:7" },
    { text: "Porque ha engrandecido sobre nosotros su misericordia.", reference: "Salmos 117:2" },
    { text: "No me dejes desviarme de tus mandamientos.", reference: "Salmos 119:10" },
    { text: "Invocad su nombre entre los pueblos.", reference: "Salmos 105:1" },
    { text: "Abba, Padre.", reference: "Romanos 8:15" },
    { text: "Dios mío, te exaltaré.", reference: "Salmos 118:28" },
    { text: "Vuestro Padre sabe de qué cosas tenéis necesidad.", reference: "Mateo 6:8" },
    { text: "Si Dios es por nosotros, ¿quién contra nosotros?", reference: "Romanos 8:31" },
    { text: "Porque por gracia ustedes han sido salvados mediante la fe; esto no procede de ustedes, sino que es el regalo de Dios.", reference: "Efesios 2:8" },
    { text: "Quien hace mis pies como de ciervas.", reference: "Salmos 18:33" },
    { text: "Y la fidelidad de Jehová es para siempre.", reference: "Salmos 117:2" },
    { text: "Porque ¿quién es Dios sino solo Jehová?", reference: "Salmos 18:31" },
    { text: "Los ojos de Jehová están en todo lugar.", reference: "Proverbios 15:3" },
    { text: "Para no pecar contra ti.", reference: "Salmos 119:11" },
    { text: "No me elegisteis vosotros a mí, sino que yo os elegí a vosotros.", reference: "Juan 15:16" },
    { text: "Jehová guardará tu salida y tu entrada.", reference: "Salmos 121:8" },
    { text: "Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá.", reference: "Mateo 7:7" },
    { text: "Si confesares con tu boca que Jesús es el Señor, serás salvo.", reference: "Romanos 10:9" },
    { text: "Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza.", reference: "Gálatas 5:22-23" },
    { text: "Andaré delante de Jehová.", reference: "Salmos 116:9" },
    { text: "Yo soy el Alfa y la Omega.", reference: "Apocalipsis 1:8" },
    { text: "Pueblos todos, alabadle.", reference: "Salmos 117:1" },
    { text: "Para hacerlos sentar con los príncipes.", reference: "Salmos 113:8" },
    { text: "Y fuiste mi salvación.", reference: "Salmos 118:21" },
    { text: "Cuando aprendiere tus justos juicios.", reference: "Salmos 119:7" },
    { text: "Por nada estéis afanosos; antes bien, en todo, mediante oración y ruego con acción de gracias, sean dadas a conocer vuestras peticiones delante de Dios.", reference: "Filipenses 4:6" },
    { text: "Vuestro corazón no se turbe.", reference: "Juan 14:1" },
    { text: "Amad a vuestros enemigos.", reference: "Mateo 5:44" },
    { text: "Pero los que confían en el Señor renovarán sus fuerzas; volarán como las águilas: correrán y no se fatigarán, caminarán y no se cansarán.", reference: "Isaías 40:31" },
    { text: "Él hace habitar en familia a la estéril.", reference: "Salmos 113:9" },
    { text: "Para guardar tus estatutos.", reference: "Salmos 119:5" },
    { text: "Y me hace estar firme en mis alturas.", reference: "Salmos 18:33" },
    { text: "Jehová es mi luz y mi salvación; ¿de quién temeré? Jehová es la fortaleza de mi vida; ¿de quién he de atemorizarme?", reference: "Salmos 27:1" },
    { text: "El que ama a Dios, ame también a su hermano.", reference: "1 Juan 4:21" },
    { text: "Sobrellevaos los unos a las cargas de los otros, y cumplid así la ley de Cristo.", reference: "Gálatas 6:2" },
    { text: "Cantad a Jehová cántico nuevo.", reference: "Salmos 96:1" },
    { text: "Por tanto, le invocaré en todos mis días.", reference: "Salmos 116:2" },
    { text: "Yo deshice como nube tus rebeliones.", reference: "Isaías 44:22" },
    { text: "Deléitate en el Señor, y él te concederá los deseos de tu corazón.", reference: "Salmos 37:4" },
    { text: "Como el ciervo brama por las corrientes de las aguas, así clama por ti, oh Dios, el alma mía.", reference: "Salmos 42:1" },
    { text: "Tu diestra me sustentó.", reference: "Salmos 18:35" },
    { text: "En toda la tierra están sus juicios.", reference: "Salmos 105:7" },
    { text: "Porque donde esté vuestro tesoro, allí estará también vuestro corazón.", reference: "Mateo 6:21" },
    { text: "El Señor es bueno, un refugio en el día de la angustia; él conoce a los que en él confían.", reference: "Nahúm 1:7" },
    { text: "El varón prudente edifica su casa sobre la roca.", reference: "Mateo 7:24" },
    { text: "La caridad nunca decae.", reference: "1 Corintios 13:8" },
    { text: "Ojalá fuesen ordenados mis caminos.", reference: "Salmos 119:5" },
    { text: "Dios es el que me ciñe de poder.", reference: "Salmos 18:32" },
    { text: "Buscad siempre su rostro.", reference: "Salmos 105:4" },
    { text: "Sea el nombre de Jehová bendito.", reference: "Salmos 113:2" },
    { text: "Amo a Jehová, pues ha oído mi voz.", reference: "Salmos 116:1" },
    { text: "Y enaltecido sea el Dios de mi salvación.", reference: "Salmos 18:46" },
    { text: "Mejor es confiar en Jehová que confiar en el hombre.", reference: "Salmos 118:8" },
    { text: "Yo soy el buen pastor; el buen pastor su vida da por las ovejas.", reference: "Juan 10:11" },
    { text: "Tu misericordia es mejor que la vida.", reference: "Salmos 63:3" },
    { text: "Fuerte es el Señor nuestro Dios.", reference: "Apocalipsis 18:8" },
    { text: "Dad gracias en todo, porque esta es la voluntad de Dios para con vosotros en Cristo Jesús.", reference: "1 Tesalonicenses 5:18" },
    { text: "Jehová es Dios, y nos ha dado luz.", reference: "Salmos 118:27" },
    { text: "Ahora pagaré mis votos a Jehová.", reference: "Salmos 116:14" },
    { text: "Te ruego, oh Jehová, que nos hagas prosperar ahora.", reference: "Salmos 118:25" },
    { text: "Someteos, pues, a Dios; resistid al diablo, y huirá de vosotros.", reference: "Santiago 4:7" },
    { text: "El deseo de los impíos perecerá.", reference: "Salmos 112:10" },
    { text: "Y con todo el corazón le buscan.", reference: "Salmos 119:2" },
    { text: "Aleluya, Bienaventurado el hombre que teme a Jehová.", reference: "Salmos 112:1" },
    { text: "Sean fuertes y valientes. No teman ni se asusten ante esas naciones, pues el Señor su Dios siempre los acompañará; nunca los dejará ni los abandonará.", reference: "Deuteronomio 31:6" },
    { text: "Porque Jehová te ha hecho bien.", reference: "Salmos 116:7" },
    { text: "Y seré salvo de mis enemigos.", reference: "Salmos 18:3" },
    { text: "La piedra que desecharon los edificadores ha venido a ser cabeza del ángulo.", reference: "Salmos 118:22" },
    { text: "Buscad a Jehová mientras puede ser hallado.", reference: "Isaías 55:6" },
    { text: "La gracia de nuestro Señor Jesucristo sea con vosotros.", reference: "1 Tesalonicenses 5:28" },
    { text: "Grande es tu fidelidad.", reference: "Lamentaciones 3:23" },
    { text: "Contigo desbarataré ejércitos.", reference: "Salmos 18:29" },
    { text: "Su justicia permanece para siempre.", reference: "Salmos 112:3" },
    { text: "Desde ahora y para siempre.", reference: "Salmos 113:2" },
    { text: "El temor de Jehová es el principio de la sabiduría.", reference: "Proverbios 1:7" },
    { text: "Buscad primero el reino de Dios y su justicia, y todas estas cosas os serán añadidas.", reference: "Mateo 6:33" },
    { text: "Resplandeció en las tinieblas luz a los rectos.", reference: "Salmos 112:4" },
    { text: "Se acordó para siempre de su pacto.", reference: "Salmos 105:8" },
    { text: "Sí, misericordioso es nuestro Dios.", reference: "Salmos 116:5" },
    { text: "Buscad la paz, y seguidla.", reference: "Salmos 34:14" },
    { text: "Y mis súplicas.", reference: "Salmos 116:1" },
    { text: "Mejor es dar que recibir.", reference: "Hechos 20:35" },
    { text: "Y mi clamor llegó delante de él, a sus oídos.", reference: "Salmos 18:6" },
    { text: "Entraré por ellas, alabaré a JAH.", reference: "Salmos 118:19" },
    { text: "Hermanos, orad por nosotros.", reference: "1 Tesalonicenses 5:25" },
    { text: "No se cansen de hacer el bien, porque a su debido tiempo cosecharemos si no nos damos por vencidos.", reference: "Gálatas 6:9" },
    { text: "El Señor es mi pastor, nada me falta.", reference: "Salmos 23:1" },
    { text: "Porque para siempre es su misericordia.", reference: "Salmos 118:1" },
    { text: "Dios es amor.", reference: "1 Juan 4:8" },
    { text: "¿Qué pagaré a Jehová por todos sus beneficios?", reference: "Salmos 116:12" },
    { text: "Lavad vuestro corazón.", reference: "Jeremías 4:14" },
    { text: "Y acrisolada la palabra de Jehová.", reference: "Salmos 18:30" },
    { text: "Buscad a Jehová y su poder.", reference: "Salmos 105:4" },
    { text: "Me sacó a lugar espacioso.", reference: "Salmos 18:19" },
    { text: "Ustedes son la luz del mundo. Una ciudad en lo alto de una colina no puede esconderse.", reference: "Mateo 5:14" },
    { text: "Sana tu alma, porque contra ti he pecado.", reference: "Salmos 41:4" },
    { text: "Bendito tú, oh Jehová.", reference: "Salmos 119:12" },
    { text: "Alabad a Jehová, naciones todas.", reference: "Salmos 117:1" },
    { text: "Crea en mí, Dios, un corazón limpio.", reference: "Salmos 51:10" },
    { text: "¿Quién como Jehová nuestro Dios?", reference: "Salmos 113:5" },
    { text: "Ensanchaste mis pasos debajo de mí.", reference: "Salmos 18:36" },
    { text: "Bienaventurados los limpios de corazón.", reference: "Mateo 5:8" },
    { text: "La gracia de nuestro Señor Jesucristo sea con todos vosotros. Amén.", reference: "Apocalipsis 22:21" },
    { text: "En tus mandamientos meditaré.", reference: "Salmos 119:15" },
    { text: "Te alabaré porque me has oído.", reference: "Salmos 118:21" },
    { text: "Yo soy la vid, vosotros los pámpanos.", reference: "Juan 15:5" },
    { text: "El hombre de bien tiene misericordia, y presta.", reference: "Salmos 112:5" },
    { text: "El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.", reference: "Salmos 91:1" },
    { text: "Gustad, y ved que es bueno Jehová.", reference: "Salmos 34:8" },
    { text: "Todo lo que respira alabe a JAH.", reference: "Salmos 150:6" },
    { text: "Sobre toda cosa guardada, guarda tu corazón.", reference: "Proverbios 4:23" },
    { text: "Todas vuestras cosas sean hechas con amor.", reference: "1 Corintios 16:14" },
    { text: "Misericordioso y clemente es Jehová.", reference: "Salmos 103:8" },
    { text: "Y al menesteroso alza del muladar.", reference: "Salmos 113:7" },
    { text: "Pónganse ante su presencia con cánticos de júbilo.", reference: "Salmos 100:2" },
    { text: "Al que al Señor busca, no le falta ningún bien.", reference: "Salmos 34:10" },
    { text: "La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo.", reference: "Juan 14:27" },
    { text: "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo.", reference: "Isaías 41:10" },
    { text: "De parte de Jehová es esto.", reference: "Salmos 118:23" },
    { text: "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.", reference: "Salmos 46:1" },
    { text: "Con guardar tu palabra.", reference: "Salmos 119:9" },
    { text: "Cristo vive en mí.", reference: "Gálatas 2:20" },
    { text: "Lo verá el impío y se despechará.", reference: "Salmos 112:10" },
    { text: "Encomienda al Señor tu camino; confía en él, y él actuará.", reference: "Salmos 37:5" },
    { text: "Pues no hacen iniquidad.", reference: "Salmos 119:3" },
    { text: "Mejor es confiar en Jehová que confiar en príncipes.", reference: "Salmos 118:9" },
    { text: "Por sus atrios con alabanza.", reference: "Salmos 100:4" },
    { text: "Abre mis ojos, y miraré las maravillas de tu ley.", reference: "Salmos 119:18" },
    { text: "Me he gozado en el camino de tus testimonios.", reference: "Salmos 119:14" },
    { text: "No juzguéis, para que no seáis juzgados.", reference: "Mateo 7:1" },
    { text: "Entrad por sus puertas con acción de gracias.", reference: "Salmos 100:4" },
    { text: "Esta es puerta de Jehová.", reference: "Salmos 118:20" },
    { text: "El que tiene oído, oiga lo que el Espíritu dice.", reference: "Apocalipsis 2:7" },
    { text: "El que cree en mí, tiene vida eterna.", reference: "Juan 6:47" },
    { text: "La oración eficaz del justo puede mucho.", reference: "Santiago 5:16" },
    { text: "He aquí que yo hago cosa nueva.", reference: "Isaías 43:19" },
    { text: "Pueblo suyo somos, y ovejas de su prado.", reference: "Salmos 100:3" },
    { text: "¿Y qué roca hay fuera de nuestro Dios?", reference: "Salmos 18:31" },
    { text: "Porque ha inclinado a mí su oído.", reference: "Salmos 116:2" },
    { text: "No te dejes vencer por el mal, sino vence al mal con el bien.", reference: "Romanos 12:21" },
    { text: "Siervo tuyo soy, hijo de tu sierva.", reference: "Salmos 116:16" },
    { text: "Mi escudo y mi fuerte salvación.", reference: "Salmos 18:2" },
    { text: "Estaba yo postrado, y me salvó.", reference: "Salmos 116:6" },
    { text: "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.", reference: "Mateo 11:28" },
    { text: "Me diste asimismo el escudo de tu salvación.", reference: "Salmos 18:35" },
    { text: "Voz de júbilo y de salvación hay en las tiendas de los justos.", reference: "Salmos 118:15" },
    { text: "Y quien hace perfecto mi camino.", reference: "Salmos 18:32" },
    { text: "Acordaos de las maravillas que él ha hecho.", reference: "Salmos 105:5" },
    { text: "Invocaré a Jehová, quien es digno de ser alabado.", reference: "Salmos 18:3" },
    { text: "Clama a mí, y yo te responderé.", reference: "Jeremías 33:3" },
    { text: "Tomaré la copa de la salvación.", reference: "Salmos 116:13" },
    { text: "Engañosa es la gracia, y vana la hermosura; la mujer que teme a Jehová, esa será alabada.", reference: "Proverbios 31:30" },
    { text: "Absteneos de toda especie de mal.", reference: "1 Tesalonicenses 5:22" },
    { text: "Ábranme las puertas de la justicia.", reference: "Salmos 118:19" },
    { text: "Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.", reference: "1 Pedro 5:7" },
    { text: "El hierro con hierro se aguza.", reference: "Proverbios 27:17" },
    { text: "Si Dios es por nosotros, ¿quién contra nosotros?", reference: "Romanos 8:31" },
    { text: "Si pues coméis, o bebéis, o hacéis otra cosa, hacedlo todo para la gloria de Dios.", reference: "1 Corintios 10:31" },
    { text: "Confía en el Señor de todo corazón, y no en tu propia inteligencia.", reference: "Proverbios 3:5" },
    { text: "Reconozcan que el Señor es Dios.", reference: "Salmos 100:3" },
    { text: "Tú encenderás mi lámpara.", reference: "Salmos 18:28" },
    { text: "Desde el nacimiento del sol hasta donde se pone.", reference: "Salmos 113:3" },
    { text: "Digan ahora los que temen a Jehová.", reference: "Salmos 118:4" },
    { text: "Excelso sobre todas las naciones es Jehová.", reference: "Salmos 113:4" },
    { text: "Porque donde están dos o tres congregados en mi nombre, allí estoy yo en medio de ellos.", reference: "Mateo 18:20" },
    { text: "Jehová está conmigo entre los que me ayudan.", reference: "Salmos 118:7" },
    { text: "No moriré, sino que viviré.", reference: "Salmos 118:17" },
    { text: "Que se sienta en las alturas.", reference: "Salmos 113:5" },
    { text: "Cantad alegremente a Dios.", reference: "Salmos 81:1" },
    { text: "Estad siempre gozosos.", reference: "1 Tesalonicenses 5:16" },
    { text: "En ti confiarán los que conocen tu nombre.", reference: "Salmos 9:10" },
    { text: "Alégrese el corazón de los que buscan a Jehová.", reference: "Salmos 105:3" },
    { text: "Su descendencia será poderosa en la tierra.", reference: "Salmos 112:2" },
    { text: "Me mostrarás la senda de la vida.", reference: "Salmos 16:11" },
    { text: "Fiel es el que os llama.", reference: "1 Tesalonicenses 5:24" },
    { text: "Alabadle con panderos y danza.", reference: "Salmos 150:4" },
    { text: "Porque Jehová es bueno; para siempre es su misericordia.", reference: "Salmos 100:5" },
    { text: "Oh Jehová, ciertamente yo soy tu siervo.", reference: "Salmos 116:16" },
    { text: "He aquí, yo estoy a la puerta y llamo; si alguno oye mi voz y abre la puerta, entraré a él, y cenaré con él, y él conmigo.", reference: "Apocalipsis 3:20" },
    { text: "Sed santos, porque yo soy santo.", reference: "1 Pedro 1:16" },
    { text: "Mis ojos de lágrimas.", reference: "Salmos 116:8" },
    { text: "Desde la angustia invoqué a JAH.", reference: "Salmos 118:5" },
    { text: "Jehová es mi pastor.", reference: "Salmos 23:1" },
    { text: "Griten de alegría al Señor, todos los habitantes de la tierra.", reference: "Salmos 100:1" },
    { text: "Sed, pues, imitadores de Dios como hijos amados.", reference: "Efesios 5:1" },
    { text: "Mi boca abrí y suspiré.", reference: "Salmos 119:131" },
    { text: "Fijemos la mirada en Jesús, el autor y consumador de la fe.", reference: "Hebreos 12:2" },
    { text: "Estimada es a los ojos de Jehová la muerte de sus santos.", reference: "Salmos 116:15" },
    { text: "E invocaré el nombre de Jehová.", reference: "Salmos 116:13" },
    { text: "¿Con qué limpiará el joven su camino?", reference: "Salmos 119:9" },
    { text: "Tus estatutos guardaré.", reference: "Salmos 119:8" },
    { text: "En la tierra de los vivientes.", reference: "Salmos 116:9" },
    { text: "El hombre propone, pero Dios dispone.", reference: "Proverbios 16:9" },
    { text: "Y me respondió JAH, poniéndome en lugar espacioso.", reference: "Salmos 118:5" },
    { text: "El Señor es mi luz.", reference: "Salmos 27:1" },
    { text: "No apaguéis al Espíritu.", reference: "1 Tesalonicenses 5:19" },
    { text: "Consideraré tus caminos.", reference: "Salmos 119:15" },
    { text: "Sirve al Señor con alegría.", reference: "Salmos 100:2" },
    { text: "Jehová es mi fortaleza y mi cántico.", reference: "Salmos 118:14" },
    { text: "Bendito sea el nombre de Jehová.", reference: "Job 1:21" },
    { text: "Invocaré el nombre de Jehová.", reference: "Salmos 116:17" },
    { text: "Que se humilla a mirar en el cielo y en la tierra.", reference: "Salmos 113:6" },
    { text: "Vuelve, oh alma mía, a tu reposo.", reference: "Salmos 116:7" },
    { text: "Y es cosa maravillosa a nuestros ojos.", reference: "Salmos 118:23" },
    { text: "Su corazón está firme, confiado en Jehová.", reference: "Salmos 112:7" },
    { text: "Él es Jehová nuestro Dios.", reference: "Salmos 105:7" },
    { text: "Hablad de todas sus maravillas.", reference: "Salmos 105:2" },
    { text: "Y contaré las obras de JAH.", reference: "Salmos 118:17" },
    { text: "Bendito el que viene en el nombre de Jehová.", reference: "Salmos 118:26" },
    { text: "La palabra de Dios es viva y eficaz.", reference: "Hebreos 4:12" },
    { text: "Crea en mí, oh Dios, un corazón limpio, y renueva un espíritu recto dentro de mí.", reference: "Salmos 51:10" },
    { text: "Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados.", reference: "1 Juan 1:9" },
    { text: "Pan de justicia es la palabra de Dios.", reference: "Mateo 4:4" },
    { text: "El Señor es mi roca y mi fortaleza.", reference: "Salmos 18:2" },
    { text: "En memoria eterna será el justo.", reference: "Salmos 112:6" },
    { text: "Alabad el nombre de Jehová.", reference: "Salmos 113:1" },
    { text: "La gracia del Señor Jesucristo sea con vuestro espíritu. Amén.", reference: "Filipenses 4:23" },
    { text: "Os es necesario nacer de nuevo.", reference: "Juan 3:7" },
    { text: "Te ofreceré sacrificio de alabanza.", reference: "Salmos 116:17" },
    { text: "Examinadlo todo; retened lo bueno.", reference: "1 Tesalonicenses 5:21" },
    { text: "Consolaos, consolaos, pueblo mío.", reference: "Isaías 40:1" },
    { text: "Él oyó mi voz desde su templo.", reference: "Salmos 18:6" },
    { text: "Honra a tu padre y a tu madre.", reference: "Éxodo 20:12" },
    { text: "Creí; por tanto hablé.", reference: "Salmos 116:10" },
    { text: "Con los príncipes de su pueblo.", reference: "Salmos 113:8" },
    { text: "Y con mi Dios asaltaré muros.", reference: "Salmos 18:29" },
    { text: "Hagan todo con amor.", reference: "1 Corintios 16:14" },
    { text: "Tú eres mi Dios, en ti confío.", reference: "Salmos 31:14" },
    { text: "Tu palabra es una lámpara a mis pies; es una luz en mi sendero.", reference: "Salmos 119:105" },
    { text: "Por lo cual no resbalará jamás.", reference: "Salmos 112:6" },
    { text: "Instruye al niño en su camino, y aun cuando fuere viejo no se apartará de él.", reference: "Proverbios 22:6" },
    { text: "Tu justicia es justicia eterna.", reference: "Salmos 119:142" },
    { text: "Sean bondadosos y compasivos unos con otros, y perdónense mutuamente, así como Dios los perdonó a ustedes en Cristo.", reference: "Efesios 4:32" },
    { text: "Que se goza en ser madre de hijos.", reference: "Salmos 113:9" },
    { text: "Pedid, y se os dará.", reference: "Mateo 7:7" },
    { text: "Asegurado está su corazón.", reference: "Salmos 112:8" },
    { text: "El amor es paciente, es bondadoso. El amor no es envidioso ni jactancioso ni orgulloso.", reference: "1 Corintios 13:4" },
    { text: "¡Cuán preciosos me son, Dios, tus pensamientos! ¡Cuán grande es la suma de ellos!", reference: "Salmos 139:17" },
    { text: "La diestra de Jehová hace proezas.", reference: "Salmos 118:15" },
    { text: "Es clemente, misericordioso y justo.", reference: "Salmos 112:4" },
    { text: "Gobierna sus asuntos con juicio.", reference: "Salmos 112:5" },
    { text: "Bendeciré al Señor en todo tiempo.", reference: "Salmos 34:1" },
    { text: "No hurtarás.", reference: "Éxodo 20:15" },
    { text: "El Señor es mi fuerza y mi escudo; en él confió mi corazón, y fui ayudado.", reference: "Salmos 28:7" },
    { text: "Porque deseaba tus mandamientos.", reference: "Salmos 119:131" },
    { text: "Alabaré a Jehová en todo tiempo; su alabanza estará siempre en mi boca.", reference: "Salmos 34:1" },
    { text: "Haz bien a tu siervo; que viva.", reference: "Salmos 119:17" },
    { text: "Porque nada hay imposible para Dios.", reference: "Lucas 1:37" },
    { text: "Y tu benignidad me ha engrandecido.", reference: "Salmos 18:35" },
    { text: "No me dejes enteramente.", reference: "Salmos 119:8" },
    { text: "No temas, manada pequeña.", reference: "Lucas 12:32" },
    { text: "Más que en toda riqueza.", reference: "Salmos 119:14" },

    // ===== VERSÍCULOS NTV PARA JÓVENES =====
    {
        text: "Ya te lo he ordenado: ¡Sé fuerte y valiente! No tengas miedo ni te desanimes, porque el Señor tu Dios está contigo dondequiera que vayas.",
        reference: "Josué 1:9 (NTV)",
        text_en: "This is my command—be strong and courageous! Do not be afraid or discouraged. For the Lord your God is with you wherever you go.",
        reference_en: "Joshua 1:9 (NLT)",
        text_pt: "Não foi isso que eu ordenei? Seja forte e corajoso! Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar.",
        reference_pt: "Josué 1:9 (NVT)"
    },
    {
        text: "¿Cómo puede un joven mantenerse puro? Obedeciendo tu palabra.",
        reference: "Salmos 119:9 (NTV)",
        text_en: "How can a young person stay pure? By obeying your word.",
        reference_en: "Psalm 119:9 (NLT)",
        text_pt: "Como pode um jovem manter pura a sua vida? Obedecendo à tua palavra.",
        reference_pt: "Salmos 119:9 (NVT)"
    },
    {
        text: "Sobre todas las cosas, cuida tu corazón, porque este determina el rumbo de tu vida.",
        reference: "Proverbios 4:23 (NTV)",
        text_en: "Guard your heart above all else, for it determines the course of your life.",
        reference_en: "Proverbs 4:23 (NLT)",
        text_pt: "Acima de tudo, guarde o seu coração, pois dele depende toda a sua vida.",
        reference_pt: "Provérbios 4:23 (NVT)"
    },
    {
        text: "Pues todo lo puedo hacer por medio de Cristo, quien me da las fuerzas.",
        reference: "Filipenses 4:13 (NTV)",
        text_en: "For I can do everything through Christ, who gives me strength.",
        reference_en: "Philippians 4:13 (NLT)",
        text_pt: "Tudo posso naquele que me fortalece.",
        reference_pt: "Filipenses 4:13 (NVT)"
    },
    {
        text: "Pues somos la obra maestra de Dios. Él nos creó de nuevo en Cristo Jesús para que hagamos las cosas buenas que preparó para nosotros tiempo atrás.",
        reference: "Efesios 2:10 (NTV)",
        text_en: "For we are God's masterpiece. He has created us anew in Christ Jesus, so we can do the good things he planned for us long ago.",
        reference_en: "Ephesians 2:10 (NLT)",
        text_pt: "Pois somos criação de Deus, realizados em Cristo Jesus para fazermos boas obras, as quais Deus preparou antes para nós as praticarmos.",
        reference_pt: "Efésios 2:10 (NVT)"
    },
    {
        text: "No imiten las conductas ni las costumbres de este mundo, más bien dejen que Dios los transforme en personas nuevas al cambiarles la manera de pensar.",
        reference: "Romanos 12:2 (NTV)",
        text_en: "Don't copy the behavior and customs of this world, but let God transform you into a new person by changing the way you think.",
        reference_en: "Romans 12:2 (NLT)",
        text_pt: "Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente.",
        reference_pt: "Romanos 12:2 (NVT)"
    },
    {
        text: "Te alabo porque soy una creación maravillosa; ¡tus obras son portentosas, y esto lo sé muy bien!",
        reference: "Salmos 139:14 (NTV)",
        text_en: "Thank you for making me so wonderfully complex! Your workmanship is marvelous—how well I know it.",
        reference_en: "Psalm 139:14 (NLT)",
        text_pt: "Eu te louvo porque me fizeste de modo especial e admirável. Tuas obras são maravilhosas! Disso tenho plena certeza.",
        reference_pt: "Salmos 139:14 (NVT)"
    },
    {
        text: "No digas: 'Soy demasiado joven'. Ve a donde yo te envíe y di lo que yo te ordene. Y no tengas miedo, porque yo estoy contigo y te protegeré.",
        reference: "Jeremías 1:7-8 (NTV)",
        text_en: "Don't say, 'I'm too young.' Go where I send you and say what I tell you. And don't be afraid, for I will be with you and protect you.",
        reference_en: "Jeremiah 1:7-8 (NLT)",
        text_pt: "Não diga: 'Sou muito jovem'. Vá aonde eu o enviar e diga tudo o que eu lhe ordenar. Não tenha medo, pois estou com você para protegê-lo.",
        reference_pt: "Jeremias 1:7-8 (NVT)"
    },
    {
        text: "Huye de los deseos pecaminosos propios de la juventud; persigue la justicia, la fe, el amor y la paz, junto con los que de corazón limpio invocan al Señor.",
        reference: "2 Timoteo 2:22 (NTV)",
        text_en: "Run from anything that stimulates youthful lusts. Instead, pursue righteous living, faithfulness, love, and peace. Enjoy the companionship of those who call on the Lord with pure hearts.",
        reference_en: "2 Timothy 2:22 (NLT)",
        text_pt: "Fuja dos desejos malignos da juventude e siga a justiça, a fé, o amor e a paz, com aqueles que de coração puro invocam o Senhor.",
        reference_pt: "2 Timóteo 2:22 (NVT)"
    },
    {
        text: "Pues estoy a punto de hacer algo nuevo. Ya está empezando a suceder. ¿No se dan cuenta? Estoy abriendo un camino en el desierto y ríos en lugares solitarios.",
        reference: "Isaías 43:19 (NTV)",
        text_en: "For I am about to do something new. See, I have already begun! Do you not see it? I will make a pathway through the wilderness and create rivers in the dry wasteland.",
        reference_en: "Isaiah 43:19 (NLT)",
        text_pt: "Eis que estou fazendo uma coisa nova! Ela já está surgindo! Vocês não a veem? Até no deserto vou abrir um caminho e riachos no ermo.",
        reference_pt: "Isaías 43:19 (NVT)"
    },
    {
        text: "Ustedes son la luz del mundo. Así que brillen con luz delante de todos, para que ellos puedan ver las buenas obras de ustedes y alaben al Padre que está en el cielo.",
        reference: "Mateo 5:14-16 (NTV)",
        text_en: "You are the light of the world. Let your good deeds shine out for all to see, so that everyone will praise your heavenly Father.",
        reference_en: "Matthew 5:14-16 (NLT)",
        text_pt: "Vocês são a luz do mundo. Assim brilhe a luz de vocês diante dos homens, para que vejam as suas boas obras e glorifiquem ao Pai de vocês, que está nos céus.",
        reference_pt: "Mateus 5:14-16 (NVT)"
    },
    {
        text: "Mi antiguo yo ha sido crucificado con Cristo. Ya no vivo yo, sino que Cristo vive en mí. Así que vivo en este cuerpo terrenal confiando en el Hijo de Dios, quien me amó y se entregó a sí mismo por mí.",
        reference: "Gálatas 2:20 (NTV)",
        text_en: "My old self has been crucified with Christ. It is no longer I who live, but Christ lives in me. So I live in this earthly body by trusting in the Son of God, who loved me and gave himself for me.",
        reference_en: "Galatians 2:20 (NLT)",
        text_pt: "Fui crucificado com Cristo. Assim, já não sou eu quem vive, mas Cristo vive em mim. A vida que agora vivo no corpo, vivo-a pela fé no Filho de Deus, que me amou e se entregou por mim.",
        reference_pt: "Gálatas 2:20 (NVT)"
    },
    {
        text: "Y sabemos que Dios hace que todas las cosas cooperen para el bien de quienes lo aman y son llamados según el propósito que él tiene para ellos.",
        reference: "Romanos 8:28 (NTV)",
        text_en: "And we know that God causes everything to work together for the good of those who love God and are called according to his purpose for them.",
        reference_en: "Romans 8:28 (NLT)",
        text_pt: "Sabemos que Deus age em todas as coisas para o bem daqueles que o amam, dos que foram chamados de acordo com o seu propósito.",
        reference_pt: "Romanos 8:28 (NVT)"
    },
    {
        text: "No juzguen a otros por su apariencia exterior, sino juzguen con justicia.",
        reference: "Juan 7:24 (NTV)",
        text_en: "Look beneath the surface so you can judge correctly.",
        reference_en: "John 7:24 (NLT)",
        text_pt: "Não julguem pela aparência, mas julguem com justiça.",
        reference_pt: "João 7:24 (NVT)"
    },
    {
        text: "Que nadie te quite el gozo de servir al Señor. El Señor está cerca.",
        reference: "Filipenses 4:5 (NTV)",
        text_en: "Let everyone see that you are considerate in all you do. Remember, the Lord is coming soon.",
        reference_en: "Philippians 4:5 (NLT)",
        text_pt: "Seja conhecida de todos a sua amabilidade. Perto está o Senhor.",
        reference_pt: "Filipenses 4:5 (NVT)"
    },
];
