export interface Verse {
    text: string;
    reference: string;
}

export const verses: Verse[] = [
    { text: "Aunque ande en valle de sombra de muerte, no temeré mal alguno, porque tú estarás conmigo.", reference: "Salmos 23:4" },
    { text: "Entonces no sería yo avergonzado.", reference: "Salmos 119:6" },
    { text: "Mi alto refugio.", reference: "Salmos 18:2" },
    { text: "Porque para mí el vivir es Cristo, y el morir es ganancia.", reference: "Filipenses 1:21" },
    { text: "La blanda respuesta quita la ira.", reference: "Proverbios 15:1" },
    { text: "Al atender a todos tus mandamientos.", reference: "Salmos 119:6" },
    { text: "Todo tiene su tiempo.", reference: "Eclesiastés 3:1" },
    { text: "Estando afligido en gran manera.", reference: "Salmos 116:10" },
    { text: "Sobre los cielos su gloria.", reference: "Salmos 113:4" },
    { text: "Yo soy la luz del mundo; el que me sigue, no andará en tinieblas, sino que tendrá la luz de la vida.", reference: "Juan 8:12" },
    { text: "En mi angustia invoqué a Jehová, y clamé a mi Dios.", reference: "Salmos 18:6" },
    { text: "Él es el que nos hizo, y no nosotros a nosotros mismos.", reference: "Salmos 100:3" },
    { text: "Alabad a Jehová, porque él es bueno.", reference: "Salmos 118:1" },
    { text: "En él confiaré; mi escudo, y la fuerza de mi salvación.", reference: "Salmos 18:2" },
    { text: "La bondad y la misericordia me seguirán todos los días de mi vida.", reference: "Salmos 23:6" },
    { text: "Adoren al Señor con regocijo.", reference: "Salmos 100:2" },
    { text: "Mi socorro viene de Jehová, que hizo los cielos y la tierra.", reference: "Salmos 121:2" },
    { text: "Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.", reference: "Juan 14:6" },
    { text: "Y todo lo que hagan, de palabra o de obra, háganlo todo en el nombre del Señor Jesús, dando gracias a Dios el Padre por medio de él.", reference: "Colosenses 3:17" },
    { text: "Gloriaos en su santo nombre.", reference: "Salmos 105:3" },
    { text: "El que persevera hasta el fin, este será salvo.", reference: "Mateo 24:13" },
    { text: "Te alabaré con rectitud de corazón.", reference: "Salmos 119:7" },
    { text: "Mi libertador, Dios mío, fortaleza mía.", reference: "Salmos 18:2" },
    { text: "Mira mi aflicción, y líbrame.", reference: "Salmos 119:153" },
    { text: "El que tenga sed, venga.", reference: "Apocalipsis 22:17" },
    { text: "Este es el día que hizo Jehová; nos gozaremos y alegraremos en él.", reference: "Salmos 118:24" },
    { text: "El Señor es mi roca.", reference: "Salmos 18:2" },
    { text: "Desde la casa de Jehová os bendecimos.", reference: "Salmos 118:26" },
    { text: "Nadie te menosprecie por ser joven. Al contrario, que los creyentes vean en ti un ejemplo a seguir en la manera de hablar, en la conducta, y en amor, fe y pureza.", reference: "1 Timoteo 4:12" },
    { text: "Mi Dios eres tú, y te alabaré.", reference: "Salmos 118:28" },
    { text: "No se inquieten por nada; más bien, en toda ocasión, con oración y ruego, presenten sus peticiones a Dios y denle gracias.", reference: "Filipenses 4:6" },
    { text: "Alegraos siempre en el Señor. Otra vez digo: ¡Alegraos!", reference: "Filipenses 4:4" },
    { text: "Porque tanto amó Dios al mundo que dio a su Hijo unigénito, para que todo el que cree en él no se pierda, sino que tenga vida eterna.", reference: "Juan 3:16" },
    { text: "En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.", reference: "Juan 16:33" },
    { text: "Sea alabado el nombre de Jehová.", reference: "Salmos 113:3" },
    { text: "Por ella entrarán los justos.", reference: "Salmos 118:20" },
    { text: "Sin fe es imposible agradar a Dios.", reference: "Hebreos 11:6" },
    { text: "Llevad mi yugo sobre vosotros.", reference: "Mateo 11:29" },
    { text: "Siete veces cae el justo, y vuelve a levantarse.", reference: "Proverbios 24:16" },
    { text: "Tú has roto mis prisiones.", reference: "Salmos 116:16" },
    { text: "Jehová mi Dios alumbrará mis tinieblas.", reference: "Salmos 18:28" },
    { text: "Escudo es a todos los que en él esperan.", reference: "Salmos 18:30" },
    { text: "Delante de todo su pueblo.", reference: "Salmos 116:14" },
    { text: "Dejad a los niños venir a mí, y no se lo impidáis; porque de los tales es el reino de Dios.", reference: "Marcos 10:14" },
    { text: "Por tanto, id, y haced discípulos a todas las naciones.", reference: "Mateo 28:19" },
    { text: "Como aguas frías al alma sedienta, así son las buenas nuevas.", reference: "Proverbios 25:25" },
    { text: "Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.", reference: "Filipenses 4:7" },
    { text: "Porque el Espíritu que Dios nos ha dado no nos hace cobardes, sino que nos da poder, amor y dominio propio.", reference: "2 Timoteo 1:7" },
    { text: "En cuanto a Dios, perfecto es su camino.", reference: "Salmos 18:30" },
    { text: "La exposición de tus palabras alumbra.", reference: "Salmos 119:130" },
    { text: "Cantadle, cantadle salmos.", reference: "Salmos 105:2" },
    { text: "Clemente es Jehová, y justo.", reference: "Salmos 116:5" },
    { text: "Amén, Aleluya.", reference: "Apocalipsis 19:4" },
    { text: "Bienaventurados los que guardan sus testimonios.", reference: "Salmos 119:2" },
    { text: "Alabadle, bendecid su nombre.", reference: "Salmos 100:4" },
    { text: "Oh Jehová, sálvanos ahora, te ruego.", reference: "Salmos 118:25" },
    { text: "El corazón alegre hermosea el rostro.", reference: "Proverbios 15:13" },
    { text: "Jehová está conmigo; no temeré lo que me pueda hacer el hombre.", reference: "Salmos 118:6" },
    { text: "Toda la Escritura es inspirada por Dios.", reference: "2 Timoteo 3:16" },
    { text: "Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo en dondequiera que vayas.", reference: "Josué 1:9" },
    { text: "Tú encargaste que sean muy guardados tus mandamientos.", reference: "Salmos 119:4" },
    { text: "Repartió, dio a los pobres.", reference: "Salmos 112:9" },
    { text: "Con mis labios he contado todos los juicios de tu boca.", reference: "Salmos 119:13" },
    { text: "Estad quietos, y conoced que yo soy Dios.", reference: "Salmos 46:10" },
    { text: "Aleluya, Bienaventurados los perfectos de camino.", reference: "Salmos 119:1" },
    { text: "Los que andan en la ley de Jehová.", reference: "Salmos 119:1" },
    { text: "En los mandamientos de Dios se deleita en gran manera.", reference: "Salmos 112:1" },
    { text: "Pues tú has librado mi alma de la muerte.", reference: "Salmos 116:8" },
    { text: "No me olvidaré de tus palabras.", reference: "Salmos 119:16" },
    { text: "Jehová es mi fortaleza y mi escudo.", reference: "Salmos 28:7" },
    { text: "Clama a mí, y yo te responderé, y te enseñaré cosas grandes y ocultas que tú no conoces.", reference: "Jeremías 33:3" },
    { text: "Alabad, siervos de Jehová.", reference: "Salmos 113:1" },
    { text: "Hijo mío, dame tu corazón.", reference: "Proverbios 23:26" },
    { text: "Hace entender a los simples.", reference: "Salmos 119:130" },
    { text: "En mi corazón he guardado tus dichos.", reference: "Salmos 119:11" },
    { text: "Lámpara es a mis pies tu palabra, y lumbrera a mi camino.", reference: "Salmos 119:105" },
    { text: "El mismo Dios de paz os santifique.", reference: "1 Tesalonicenses 5:23" },
    { text: "El amor nunca deja de ser.", reference: "1 Corintios 13:8" },
    { text: "No tendrá temor de malas noticias.", reference: "Salmos 112:7" },
    { text: "Porque yo sé muy bien los planes que tengo para ustedes —afirma el Señor—, planes de bienestar y no de calamidad, a fin de darles un futuro y una esperanza.", reference: "Jeremías 29:11" },
    { text: "Maranatha.", reference: "1 Corintios 16:22" },
    { text: "Diga ahora Israel.", reference: "Salmos 118:2" },
    { text: "Humillaos, pues, bajo la poderosa mano de Dios, para que él os exalte cuando fuere tiempo.", reference: "1 Pedro 5:6" },
    { text: "Y guarde tu palabra.", reference: "Salmos 119:17" },
    { text: "Y mis pies no han resbalado.", reference: "Salmos 18:36" },
    { text: "Fíate de Jehová de todo tu corazón.", reference: "Proverbios 3:5" },
    { text: "Bienes y riquezas hay en su casa.", reference: "Salmos 112:3" },
    { text: "El Señor de paz os dé siempre paz en toda manera.", reference: "2 Tesalonicenses 3:16" },
    { text: "Porque el Hijo del Hombre vino a buscar y a salvar lo que se había perdido.", reference: "Lucas 19:10" },
    { text: "Todo lo puedo en Cristo que me fortalece.", reference: "Filipenses 4:13" },
    { text: "Y mis pies de resbalar.", reference: "Salmos 116:8" },
    { text: "Cantad salmos a su nombre.", reference: "Salmos 68:4" },
    { text: "Jehová dio, y Jehová quitó.", reference: "Job 1:21" },
    { text: "Jehová guarda a los sencillos.", reference: "Salmos 116:6" },
    { text: "Saludad a todos los hermanos con ósculo santo.", reference: "1 Tesalonicenses 5:26" },
    { text: "No temas, gusanito de Jacob.", reference: "Isaías 41:14" },
    { text: "Venid, benditos de mi Padre.", reference: "Mateo 25:34" },
    { text: "El ángel de Jehová acampa alrededor de los que le temen.", reference: "Salmos 34:7" },
    { text: "¡Viva Jehová, y bendita sea mi roca!", reference: "Salmos 18:46" },
    { text: "Me regocijaré en tus estatutos.", reference: "Salmos 119:16" },
    { text: "Cristo nos hizo libres.", reference: "Gálatas 5:1" },
    { text: "Y él ha sido mi salvación.", reference: "Salmos 118:14" },
    { text: "Con todo mi corazón te he buscado.", reference: "Salmos 119:10" },
    { text: "Su verdad por todas las generaciones.", reference: "Salmos 100:5" },
    { text: "Gracia y paz a vosotros, de Dios nuestro Padre y del Señor Jesucristo.", reference: "1 Corintios 1:3" },
    { text: "Gracia a vosotros y paz.", reference: "Romanos 1:7" },
    { text: "Pedid por la paz de Jerusalén.", reference: "Salmos 122:6" },
    { text: "Me libró, porque se agradó de mí.", reference: "Salmos 18:19" },
    { text: "Por sus llagas fuimos nosotros curados.", reference: "Isaías 53:5" },
    { text: "Enséñame tus estatutos.", reference: "Salmos 119:12" },
    { text: "Andan en sus caminos.", reference: "Salmos 119:3" },
    { text: "La fe es la certeza de lo que se espera.", reference: "Hebreos 11:1" },
    { text: "Gozaos con los que se gozan; llorad con los que lloran.", reference: "Romanos 12:15" },
    { text: "Él levanta del polvo al pobre.", reference: "Salmos 113:7" },
    { text: "Porque ha engrandecido sobre nosotros su misericordia.", reference: "Salmos 117:2" },
    { text: "No me dejes desviarme de tus mandamientos.", reference: "Salmos 119:10" },
    { text: "Invocad su nombre entre los pueblos.", reference: "Salmos 105:1" },
    { text: "Abba, Padre.", reference: "Romanos 8:15" },
    { text: "Dios mío, te exaltaré.", reference: "Salmos 118:28" },
    { text: "Vuestro Padre sabe de qué cosas tenéis necesidad.", reference: "Mateo 6:8" },
    { text: "Si Dios es por nosotros, ¿quién contra nosotros?", reference: "Romanos 8:31" },
    { text: "Porque por gracia ustedes han sido salvados mediante la fe; esto no procede de ustedes, sino que es el regalo de Dios.", reference: "Efesios 2:8" },
    { text: "Quien hace mis pies como de ciervas.", reference: "Salmos 18:33" },
    { text: "Y la fidelidad de Jehová es para siempre.", reference: "Salmos 117:2" },
    { text: "Porque ¿quién es Dios sino solo Jehová?", reference: "Salmos 18:31" },
    { text: "Los ojos de Jehová están en todo lugar.", reference: "Proverbios 15:3" },
    { text: "Para no pecar contra ti.", reference: "Salmos 119:11" },
    { text: "No me elegisteis vosotros a mí, sino que yo os elegí a vosotros.", reference: "Juan 15:16" },
    { text: "Jehová guardará tu salida y tu entrada.", reference: "Salmos 121:8" },
    { text: "Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá.", reference: "Mateo 7:7" },
    { text: "Si confesares con tu boca que Jesús es el Señor, serás salvo.", reference: "Romanos 10:9" },
    { text: "Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza.", reference: "Gálatas 5:22-23" },
    { text: "Andaré delante de Jehová.", reference: "Salmos 116:9" },
    { text: "Yo soy el Alfa y la Omega.", reference: "Apocalipsis 1:8" },
    { text: "Pueblos todos, alabadle.", reference: "Salmos 117:1" },
    { text: "Para hacerlos sentar con los príncipes.", reference: "Salmos 113:8" },
    { text: "Y fuiste mi salvación.", reference: "Salmos 118:21" },
    { text: "Cuando aprendiere tus justos juicios.", reference: "Salmos 119:7" },
    { text: "Por nada estéis afanosos; antes bien, en todo, mediante oración y ruego con acción de gracias, sean dadas a conocer vuestras peticiones delante de Dios.", reference: "Filipenses 4:6" },
    { text: "Vuestro corazón no se turbe.", reference: "Juan 14:1" },
    { text: "Amad a vuestros enemigos.", reference: "Mateo 5:44" },
    { text: "Pero los que confían en el Señor renovarán sus fuerzas; volarán como las águilas: correrán y no se fatigarán, caminarán y no se cansarán.", reference: "Isaías 40:31" },
    { text: "Él hace habitar en familia a la estéril.", reference: "Salmos 113:9" },
    { text: "Para guardar tus estatutos.", reference: "Salmos 119:5" },
    { text: "Y me hace estar firme en mis alturas.", reference: "Salmos 18:33" },
    { text: "Jehová es mi luz y mi salvación; ¿de quién temeré? Jehová es la fortaleza de mi vida; ¿de quién he de atemorizarme?", reference: "Salmos 27:1" },
    { text: "El que ama a Dios, ame también a su hermano.", reference: "1 Juan 4:21" },
    { text: "Sobrellevaos los unos a las cargas de los otros, y cumplid así la ley de Cristo.", reference: "Gálatas 6:2" },
    { text: "Cantad a Jehová cántico nuevo.", reference: "Salmos 96:1" },
    { text: "Por tanto, le invocaré en todos mis días.", reference: "Salmos 116:2" },
    { text: "Yo deshice como nube tus rebeliones.", reference: "Isaías 44:22" },
    { text: "Deléitate en el Señor, y él te concederá los deseos de tu corazón.", reference: "Salmos 37:4" },
    { text: "Como el ciervo brama por las corrientes de las aguas, así clama por ti, oh Dios, el alma mía.", reference: "Salmos 42:1" },
    { text: "Tu diestra me sustentó.", reference: "Salmos 18:35" },
    { text: "En toda la tierra están sus juicios.", reference: "Salmos 105:7" },
    { text: "Porque donde esté vuestro tesoro, allí estará también vuestro corazón.", reference: "Mateo 6:21" },
    { text: "El Señor es bueno, un refugio en el día de la angustia; él conoce a los que en él confían.", reference: "Nahúm 1:7" },
    { text: "El varón prudente edifica su casa sobre la roca.", reference: "Mateo 7:24" },
    { text: "La caridad nunca decae.", reference: "1 Corintios 13:8" },
    { text: "Ojalá fuesen ordenados mis caminos.", reference: "Salmos 119:5" },
    { text: "Dios es el que me ciñe de poder.", reference: "Salmos 18:32" },
    { text: "Buscad siempre su rostro.", reference: "Salmos 105:4" },
    { text: "Sea el nombre de Jehová bendito.", reference: "Salmos 113:2" },
    { text: "Amo a Jehová, pues ha oído mi voz.", reference: "Salmos 116:1" },
    { text: "Y enaltecido sea el Dios de mi salvación.", reference: "Salmos 18:46" },
    { text: "Mejor es confiar en Jehová que confiar en el hombre.", reference: "Salmos 118:8" },
    { text: "Yo soy el buen pastor; el buen pastor su vida da por las ovejas.", reference: "Juan 10:11" },
    { text: "Tu misericordia es mejor que la vida.", reference: "Salmos 63:3" },
    { text: "Fuerte es el Señor nuestro Dios.", reference: "Apocalipsis 18:8" },
    { text: "Dad gracias en todo, porque esta es la voluntad de Dios para con vosotros en Cristo Jesús.", reference: "1 Tesalonicenses 5:18" },
    { text: "Jehová es Dios, y nos ha dado luz.", reference: "Salmos 118:27" },
    { text: "Ahora pagaré mis votos a Jehová.", reference: "Salmos 116:14" },
    { text: "Te ruego, oh Jehová, que nos hagas prosperar ahora.", reference: "Salmos 118:25" },
    { text: "Someteos, pues, a Dios; resistid al diablo, y huirá de vosotros.", reference: "Santiago 4:7" },
    { text: "El deseo de los impíos perecerá.", reference: "Salmos 112:10" },
    { text: "Y con todo el corazón le buscan.", reference: "Salmos 119:2" },
    { text: "Aleluya, Bienaventurado el hombre que teme a Jehová.", reference: "Salmos 112:1" },
    { text: "Sean fuertes y valientes. No teman ni se asusten ante esas naciones, pues el Señor su Dios siempre los acompañará; nunca los dejará ni los abandonará.", reference: "Deuteronomio 31:6" },
    { text: "Porque Jehová te ha hecho bien.", reference: "Salmos 116:7" },
    { text: "Y seré salvo de mis enemigos.", reference: "Salmos 18:3" },
    { text: "La piedra que desecharon los edificadores ha venido a ser cabeza del ángulo.", reference: "Salmos 118:22" },
    { text: "Buscad a Jehová mientras puede ser hallado.", reference: "Isaías 55:6" },
    { text: "La gracia de nuestro Señor Jesucristo sea con vosotros.", reference: "1 Tesalonicenses 5:28" },
    { text: "Grande es tu fidelidad.", reference: "Lamentaciones 3:23" },
    { text: "Contigo desbarataré ejércitos.", reference: "Salmos 18:29" },
    { text: "Su justicia permanece para siempre.", reference: "Salmos 112:3" },
    { text: "Desde ahora y para siempre.", reference: "Salmos 113:2" },
    { text: "El temor de Jehová es el principio de la sabiduría.", reference: "Proverbios 1:7" },
    { text: "Buscad primero el reino de Dios y su justicia, y todas estas cosas os serán añadidas.", reference: "Mateo 6:33" },
    { text: "Resplandeció en las tinieblas luz a los rectos.", reference: "Salmos 112:4" },
    { text: "Se acordó para siempre de su pacto.", reference: "Salmos 105:8" },
    { text: "Sí, misericordioso es nuestro Dios.", reference: "Salmos 116:5" },
    { text: "Buscad la paz, y seguidla.", reference: "Salmos 34:14" },
    { text: "Y mis súplicas.", reference: "Salmos 116:1" },
    { text: "Mejor es dar que recibir.", reference: "Hechos 20:35" },
    { text: "Y mi clamor llegó delante de él, a sus oídos.", reference: "Salmos 18:6" },
    { text: "Entraré por ellas, alabaré a JAH.", reference: "Salmos 118:19" },
    { text: "Hermanos, orad por nosotros.", reference: "1 Tesalonicenses 5:25" },
    { text: "No se cansen de hacer el bien, porque a su debido tiempo cosecharemos si no nos damos por vencidos.", reference: "Gálatas 6:9" },
    { text: "El Señor es mi pastor, nada me falta.", reference: "Salmos 23:1" },
    { text: "Porque para siempre es su misericordia.", reference: "Salmos 118:1" },
    { text: "Dios es amor.", reference: "1 Juan 4:8" },
    { text: "¿Qué pagaré a Jehová por todos sus beneficios?", reference: "Salmos 116:12" },
    { text: "Lavad vuestro corazón.", reference: "Jeremías 4:14" },
    { text: "Y acrisolada la palabra de Jehová.", reference: "Salmos 18:30" },
    { text: "Buscad a Jehová y su poder.", reference: "Salmos 105:4" },
    { text: "Me sacó a lugar espacioso.", reference: "Salmos 18:19" },
    { text: "Ustedes son la luz del mundo. Una ciudad en lo alto de una colina no puede esconderse.", reference: "Mateo 5:14" },
    { text: "Sana tu alma, porque contra ti he pecado.", reference: "Salmos 41:4" },
    { text: "Bendito tú, oh Jehová.", reference: "Salmos 119:12" },
    { text: "Alabad a Jehová, naciones todas.", reference: "Salmos 117:1" },
    { text: "Crea en mí, Dios, un corazón limpio.", reference: "Salmos 51:10" },
    { text: "¿Quién como Jehová nuestro Dios?", reference: "Salmos 113:5" },
    { text: "Ensanchaste mis pasos debajo de mí.", reference: "Salmos 18:36" },
    { text: "Bienaventurados los limpios de corazón.", reference: "Mateo 5:8" },
    { text: "La gracia de nuestro Señor Jesucristo sea con todos vosotros. Amén.", reference: "Apocalipsis 22:21" },
    { text: "En tus mandamientos meditaré.", reference: "Salmos 119:15" },
    { text: "Te alabaré porque me has oído.", reference: "Salmos 118:21" },
    { text: "Yo soy la vid, vosotros los pámpanos.", reference: "Juan 15:5" },
    { text: "El hombre de bien tiene misericordia, y presta.", reference: "Salmos 112:5" },
    { text: "El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.", reference: "Salmos 91:1" },
    { text: "Gustad, y ved que es bueno Jehová.", reference: "Salmos 34:8" },
    { text: "Todo lo que respira alabe a JAH.", reference: "Salmos 150:6" },
    { text: "Sobre toda cosa guardada, guarda tu corazón.", reference: "Proverbios 4:23" },
    { text: "Todas vuestras cosas sean hechas con amor.", reference: "1 Corintios 16:14" },
    { text: "Misericordioso y clemente es Jehová.", reference: "Salmos 103:8" },
    { text: "Y al menesteroso alza del muladar.", reference: "Salmos 113:7" },
    { text: "Pónganse ante su presencia con cánticos de júbilo.", reference: "Salmos 100:2" },
    { text: "Al que al Señor busca, no le falta ningún bien.", reference: "Salmos 34:10" },
    { text: "La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo.", reference: "Juan 14:27" },
    { text: "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo.", reference: "Isaías 41:10" },
    { text: "De parte de Jehová es esto.", reference: "Salmos 118:23" },
    { text: "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.", reference: "Salmos 46:1" },
    { text: "Con guardar tu palabra.", reference: "Salmos 119:9" },
    { text: "Cristo vive en mí.", reference: "Gálatas 2:20" },
    { text: "Lo verá el impío y se despechará.", reference: "Salmos 112:10" },
    { text: "Encomienda al Señor tu camino; confía en él, y él actuará.", reference: "Salmos 37:5" },
    { text: "Pues tú has librado mi alma de la muerte.", reference: "Salmos 116:8" },
    { text: "No me olvidaré de tus palabras.", reference: "Salmos 119:16" },
    { text: "Jehová es mi fortaleza y mi escudo.", reference: "Salmos 28:7" },
    { text: "Clama a mí, y yo te responderé, y te enseñaré cosas grandes y ocultas que tú no conoces.", reference: "Jeremías 33:3" },
    { text: "Alabad, siervos de Jehová.", reference: "Salmos 113:1" },
    { text: "Hijo mío, dame tu corazón.", reference: "Proverbios 23:26" },
    { text: "Hace entender a los simples.", reference: "Salmos 119:130" },
    { text: "En mi corazón he guardado tus dichos.", reference: "Salmos 119:11" },
    { text: "Lámpara es a mis pies tu palabra, y lumbrera a mi camino.", reference: "Salmos 119:105" },
    { text: "El mismo Dios de paz os santifique.", reference: "1 Tesalonicenses 5:23" },
    { text: "El amor nunca deja de ser.", reference: "1 Corintios 13:8" },
    { text: "No tendrá temor de malas noticias.", reference: "Salmos 112:7" },
    { text: "Porque yo sé muy bien los planes que tengo para ustedes —afirma el Señor—, planes de bienestar y no de calamidad, a fin de darles un futuro y una esperanza.", reference: "Jeremías 29:11" },
    { text: "Maranatha.", reference: "1 Corintios 16:22" },
    { text: "Diga ahora Israel.", reference: "Salmos 118:2" },
    { text: "Humillaos, pues, bajo la poderosa mano de Dios, para que él os exalte cuando fuere tiempo.", reference: "1 Pedro 5:6" },
    { text: "Y guarde tu palabra.", reference: "Salmos 119:17" },
    { text: "Y mis pies no han resbalado.", reference: "Salmos 18:36" },
    { text: "Fíate de Jehová de todo tu corazón.", reference: "Proverbios 3:5" },
    { text: "Bienes y riquezas hay en su casa.", reference: "Salmos 112:3" },
    { text: "El Señor de paz os dé siempre paz en toda manera.", reference: "2 Tesalonicenses 3:16" },
    { text: "Porque el Hijo del Hombre vino a buscar y a salvar lo que se había perdido.", reference: "Lucas 19:10" },
    { text: "Todo lo puedo en Cristo que me fortalece.", reference: "Filipenses 4:13" },
    { text: "Y mis pies de resbalar.", reference: "Salmos 116:8" },
    { text: "Cantad salmos a su nombre.", reference: "Salmos 68:4" },
    { text: "Jehová dio, y Jehová quitó.", reference: "Job 1:21" },
    { text: "Jehová guarda a los sencillos.", reference: "Salmos 116:6" },
    { text: "Saludad a todos los hermanos con ósculo santo.", reference: "1 Tesalonicenses 5:26" },
    { text: "No temas, gusanito de Jacob.", reference: "Isaías 41:14" },
    { text: "Venid, benditos de mi Padre.", reference: "Mateo 25:34" },
    { text: "El ángel de Jehová acampa alrededor de los que le temen.", reference: "Salmos 34:7" },
    { text: "¡Viva Jehová, y bendita sea mi roca!", reference: "Salmos 18:46" },
    { text: "Me regocijaré en tus estatutos.", reference: "Salmos 119:16" },
    { text: "Cristo nos hizo libres.", reference: "Gálatas 5:1" },
    { text: "Y él ha sido mi salvación.", reference: "Salmos 118:14" },
    { text: "Con todo mi corazón te he buscado.", reference: "Salmos 119:10" },
    { text: "Su verdad por todas las generaciones.", reference: "Salmos 100:5" },
    { text: "Gracia y paz a vosotros, de Dios nuestro Padre y del Señor Jesucristo.", reference: "1 Corintios 1:3" },
    { text: "Gracia a vosotros y paz.", reference: "Romanos 1:7" },
    { text: "Pedid por la paz de Jerusalén.", reference: "Salmos 122:6" },
    { text: "Me libró, porque se agradó de mí.", reference: "Salmos 18:19" },
    { text: "Por sus llagas fuimos nosotros curados.", reference: "Isaías 53:5" },
    { text: "Enséñame tus estatutos.", reference: "Salmos 119:12" },
    { text: "Andan en sus caminos.", reference: "Salmos 119:3" },
    { text: "La fe es la certeza de lo que se espera.", reference: "Hebreos 11:1" },
    { text: "Gozaos con los que se gozan; llorad con los que lloran.", reference: "Romanos 12:15" },
    { text: "Él levanta del polvo al pobre.", reference: "Salmos 113:7" },
    { text: "Porque ha engrandecido sobre nosotros su misericordia.", reference: "Salmos 117:2" },
    { text: "No me dejes desviarme de tus mandamientos.", reference: "Salmos 119:10" },
    { text: "Invocad su nombre entre los pueblos.", reference: "Salmos 105:1" },
    { text: "Abba, Padre.", reference: "Romanos 8:15" },
    { text: "Dios mío, te exaltaré.", reference: "Salmos 118:28" },
    { text: "Vuestro Padre sabe de qué cosas tenéis necesidad.", reference: "Mateo 6:8" },
    { text: "Si Dios es por nosotros, ¿quién contra nosotros?", reference: "Romanos 8:31" },
    { text: "Porque por gracia ustedes han sido salvados mediante la fe; esto no procede de ustedes, sino que es el regalo de Dios.", reference: "Efesios 2:8" },
    { text: "Quien hace mis pies como de ciervas.", reference: "Salmos 18:33" },
    { text: "Y la fidelidad de Jehová es para siempre.", reference: "Salmos 117:2" },
    { text: "Porque ¿quién es Dios sino solo Jehová?", reference: "Salmos 18:31" },
    { text: "Los ojos de Jehová están en todo lugar.", reference: "Proverbios 15:3" },
    { text: "Para no pecar contra ti.", reference: "Salmos 119:11" },
    { text: "No me elegisteis vosotros a mí, sino que yo os elegí a vosotros.", reference: "Juan 15:16" },
];
